//! Golden vectors of `hexx` 0.25.0 for the Cairo port, generated by `tools/refgen`:
//! the golden files of L-M2 within the budget (euclidean, swizzle, convert).
//! The tests are under `tests/` (one integration-test target); the library is empty. Never
//! published. Line budget and where a new golden file goes: `AGENTS.md`, "Golden tests".
