//! Golden vectors of `hexx` 0.25.0 for the Cairo port, generated by `tools/refgen`:
//! the golden file of `hex::grid` (`GridEdge`, `GridVertex`; M2-T7).
//! The tests are under `tests/` (one integration-test target); the library is empty. Never
//! published. Line budget and where a new golden file goes: `AGENTS.md`, "Golden tests".
