//! Golden vectors of `hexx` 0.25.0 for the Cairo port, generated by `tools/refgen`:
//! the golden file of the rings, wedges and spirals of `Hex` (M2-T4).
//! The tests are under `tests/` (one integration-test target); the library is empty. Never
//! published. Line budget and where a new golden file goes: `AGENTS.md`, "Golden tests".
