//! Golden vectors of `hexx` 0.25.0 for the rest of `Hex` (milestone L-M2, M2-T2), generated by
//! `tools/refgen`: `tests/golden_hex_t2.cairo`.
//! The tests are under `tests/` (one integration-test target); the library is empty. Never
//! published. Line budget and where a new golden file goes: `AGENTS.md`, "Golden tests".
