#!/usr/bin/env python3
"""Measures the Sierra gas of every snforge test of the workspace, enforces the budget rule
(COMMON.md §4, grimworld:docs/CAIRO.md §2) and maintains `gas/*.snap`.

The rule: every test carries `#[available_gas(l2_gas: N)]`. `N = ceil(1.05 * measured)` when a
budget is set or raised; lowering a budget needs nothing more than the lower number itself (a
cheaper measurement never has to hit the ceiling exactly to be accepted) — so `check` rejects a
budget **above** `ceil(1.05 * measured)` (more than 5 % of headroom) and a budget **below**
`measured` (the test would fail for lack of gas), and accepts anything in between. This is the
orchestrator's decision at fix loop 1 (finding 8): the auditor's suggested fix reads the rule as
an exact equality, `N = ceil(1.05 * measured)` on every check, which would force a budget churn on
every measurement drift smaller than 5 % and is not what COMMON.md §4 / `docs/CAIRO.md` §2 ask —
see the LIB-04 report, "Fix loop 1", for the dispute this records rather than applies.

This is the `origami_hexmap` form (`GAS.md` of `sources/origami/crates/hexmap`), kept because it
is what the game's rules require and what the taken-over tests already do (plan §4.2) — as
distinct from the `glam-cairo` house form (paired `X__base` / `X__op` benches, `gas/<module>.snap`
of net cost deltas): this package's tests are not written in `X__base` / `X__op` pairs, so that
form does not apply here (see the LIB-04 report for which of the two forms derives from the
other).

`gas/*.snap` is the single source of truth: `scripts/gas_tables.py` renders `docs/GAS.md` from it,
a pure function of committed data (no snforge run).

Every test is accounted for **by its full path** (`package::module::...::name` for a unit test,
`package_integrationtest::file_stem::module::...::name` for an integration test — matching what
snforge itself prints), not by function name alone — fix loop 1 finding 8: two tests with the
same short name in different modules used to collapse into one row, and a test snforge does not
measure at all (`#[ignore]`d, or excluded by a filter) produced no violation even with no budget,
because it was simply absent from `snforge`'s own output, the only thing `check` used to read.
`declared_tests` below finds every `#[test]` from the Cairo source directly (a small,
purpose-built module-path walker, not `scripts/api_parity.py`'s: that one computes *public API*
reachability, irrelevant to a private `#[cfg(test)] mod tests`, which is exactly where every unit
test of this workspace lives) — every module file reachable from `src/lib.cairo` (directory and
flat forms) and every integration test under `tests/` (fix loop 2 decision C: `declared_tests`
used to scan `src/lib.cairo` only, so an integration test under `tests/` produced no declared row
regardless of budget, and a flat file's own child module in a sibling directory was never found
at all). A `.cairo` file under `src/` or `tests/` that contains `#[test]` and that this walk never
reached is an error, not a silent skip. `check` requires every declared test to appear in what was
measured.

usage:
  scripts/bench.py run              measure every test, print a table, check nothing
  scripts/bench.py snapshot         same, then (re)write gas/<package>.snap
  scripts/bench.py check            same, then: (1) diff against gas/*.snap, exit 1 on any
                                     difference; (2) fail on any declared test that was not
                                     measured and has no budget, or whose budget is outside
                                     [measured, ceil(1.05 * measured)]; a test of
                                     gas/takeover-baseline.txt is exempt from those two rules
                                     only (see below)
  scripts/bench.py baseline         same measurement, then (re)write gas/takeover-baseline.txt;
                                     refuses to add a test to it without --allow-growth, and any
                                     test that is not inherited from the take-over, always
  scripts/bench.py baseline --inherited --source <crates/hexmap>
                                    (re)write gas/takeover-tests.txt, the tests of the pinned
                                     source that the take-over moved; `--check` verifies it (CI
                                     job `takeover`); no snforge run

The take-over baseline (`gas/takeover-baseline.txt`, task LIB-05 M1-T1a follow-up 1): the tests
taken over from `origami_hexmap` 1.8.0 keep their budgets unchanged (a pure move), and some are not
conformant today: budgets rounded up to the thousand, tests without `#[available_gas]`. The file
lists them, one full test path per line, sorted, generated by `baseline` and never by hand. A test
of the list is exempt from "has a budget" and "budget <= ceil(1.05 * measured)" and from nothing
else: it must still be discovered, measured when it is not ignored, pass, and stay within its
declared budget when it has one. A test that is not in the list obeys every rule. A test of the
list that became conformant, or that no longer exists, is an error asking to regenerate the list:
it only shrinks (task M1-T1c empties it).
"""
from __future__ import annotations

import argparse
import math
import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GAS = ROOT / "gas"
BASELINE = GAS / "takeover-baseline.txt"
BASELINE_HEADER = """\
# Take-over baseline: the tests taken over from origami_hexmap 1.8.0 (a pure move, budgets
# unchanged) whose budget is not conformant today: no #[available_gas], or a budget above
# ceil(1.05 * measured). scripts/bench.py check exempts them from those two rules and from
# nothing else.
# Generated by `python3 scripts/bench.py baseline`, never written by hand. It only shrinks:
# `baseline` refuses to add a test (--allow-growth exists, no workflow uses it), and `check` fails
# on a test that became conformant or no longer exists, asking to regenerate.
# Task M1-T1c empties it.
"""
PASS_RE = re.compile(r"^\[(PASS|FAIL)\] (\S+)")
GAS_LINE_RE = re.compile(r"^\s*sierra gas:\s*(\d+)")
AVAILABLE_GAS_RE = re.compile(r"available_gas\(\s*l2_gas\s*:\s*(\d+)\s*\)")
# An attribute may be followed by a line comment (`#[ignore] // why`), and comment lines may sit
# between the attributes and `fn` (M1-T1a fix loop 1, finding 2).
FN_RE = re.compile(r"((?:#\[[^\]]*\](?:\s|//[^\n]*)*)+)fn\s+([A-Za-z_]\w*)\s*\(")
MOD_DECL_RE = re.compile(r"(?m)^[ \t]*(?:pub\s+)?mod\s+([A-Za-z_]\w*)\s*(;|\{)")


def workspace_packages() -> dict[str, Path]:
    """package name -> its directory, from the root Scarb.toml's `[workspace] members`."""
    manifest = tomllib.loads((ROOT / "Scarb.toml").read_text())
    packages: dict[str, Path] = {}
    for member in manifest["workspace"]["members"]:
        if "*" in member:
            candidates = sorted((ROOT / member.split("*")[0]).glob("*"))
        else:
            candidates = [ROOT / member]
        for path in candidates:
            manifest_path = path / "Scarb.toml"
            if manifest_path.is_file():
                name = tomllib.loads(manifest_path.read_text())["package"]["name"]
                packages[name] = path
    return packages


def closing_brace(text: str, opening: int) -> int:
    depth = 0
    for i in range(opening, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return i
    return len(text)


def module_nodes(
    root_file: Path, root_dir: Path | None = None, root_text: str | None = None
) -> list[tuple[tuple[str, ...], str, Path]]:
    """Every module of a Cairo crate (or of one `tests/` integration-test file) as
    `(path, own_text, file)`, walked from `root_file`, the same `mod NAME;` / `mod NAME { ... }`
    syntax `scripts/api_parity.py`'s walker uses (no `pub`/private distinction here: a test can be
    private and still be a test). `path` is relative to `root_file` itself; the caller prefixes it
    with the package (and, for an integration-test root, the file's own stem).

    `root_dir` is where `root_file`'s own `mod NAME;` children resolve; it defaults to
    `root_file.parent` (`src/lib.cairo` is the crate root, so its children sit directly in `src/`).
    A `tests/<stem>.cairo` integration-test root is itself a *flat file*, not a crate root: its own
    children resolve in the sibling directory named after it (`tests/<stem>/`), exactly like any
    other flat file's children one level down — the caller passes that directory explicitly."""
    nodes: list[tuple[tuple[str, ...], str, Path]] = []

    def visit(path: tuple[str, ...], dir_path: Path, text: str, file: Path) -> None:
        chars = list(text)
        consumed_until = 0
        children: list[tuple[str, str | None]] = []
        for m in MOD_DECL_RE.finditer(text):
            if m.start() < consumed_until:
                continue
            name, term = m.group(1), m.group(2)
            if term == ";":
                children.append((name, None))
                end = m.end()
            else:
                open_pos = m.end() - 1
                close_pos = closing_brace(text, open_pos)
                children.append((name, text[open_pos + 1:close_pos]))
                end = close_pos + 1
            for i in range(m.start(), end):
                if chars[i] != "\n":
                    chars[i] = " "
            consumed_until = end
        nodes.append((path, "".join(chars), file))
        for name, inline_body in children:
            child_path = path + (name,)
            if inline_body is not None:
                visit(child_path, dir_path, inline_body, file)
                continue
            flat = dir_path / f"{name}.cairo"
            nested = dir_path / name / "mod.cairo"
            if flat.is_file():
                # `name`'s own further children (if `name.cairo` itself declares `mod
                # grandchild;`) resolve in a sibling directory named after it (`dir_path/name/`),
                # exactly as for the `X/mod.cairo` form below — the same bug `scripts/api_parity.py`
                # had (fix loop 2 finding 4/8): this used to pass `dir_path` unchanged, so a flat
                # parent's own child module (`foo.cairo` declaring `mod bar;`, real file
                # `foo/bar.cairo`) was never discovered.
                visit(child_path, dir_path / name, flat.read_text(), flat)
            elif nested.is_file():
                visit(child_path, dir_path / name, nested.read_text(), nested)
            # else: declared but the file does not exist (should not happen in a building
            # workspace) — skip rather than fail a gas check on a missing-file build error. A
            # `#[test]` left behind in an orphaned file is still caught: `declared_tests` below
            # separately walks every `.cairo` file under `src/` and `tests/` and errors on any
            # that this traversal never visited.

    if root_text is not None:
        # The text of the root is given (a source file after the rewrites of the take-over).
        visit((), root_dir if root_dir is not None else root_file.parent, root_text, root_file)
    elif root_file.is_file():
        visit((), root_dir if root_dir is not None else root_file.parent, root_file.read_text(),
              root_file)
    return nodes


def integration_test_roots(package_dir: Path) -> list[tuple[str, Path]]:
    """`(file_stem, file)` for every top-level `*.cairo` file directly under `tests/`: each is its
    own snforge integration-test crate root, printed as `<package>_integrationtest::<file_stem>::
    ...` — confirmed empirically against snforge 0.61.0 (`tests/flat.cairo`'s own `mod sub;`
    resolves in the sibling directory `tests/flat/sub.cairo`, exactly `src/`'s flat-file
    convention; a directory directly under `tests/` with no matching top-level file, or vice
    versa, is not a form snforge itself accepts, so it is not handled here)."""
    tests_dir = package_dir / "tests"
    if not tests_dir.is_dir():
        return []
    return sorted((p.stem, p) for p in tests_dir.glob("*.cairo"))


def tests_of_nodes(prefix: tuple[str, ...],
                   nodes: list[tuple[tuple[str, ...], str, Path]]) -> dict[str, int | None]:
    """Full test name -> declared `l2_gas` budget (or None) for the `#[test]` functions of nodes."""
    tests: dict[str, int | None] = {}
    for path, text, _file in nodes:
        for match in FN_RE.finditer(text):
            attrs, name = match.group(1), match.group(2)
            if "#[test]" not in attrs:
                continue
            gas_match = AVAILABLE_GAS_RE.search(attrs)
            tests["::".join((*prefix, *path, name))] = (
                int(gas_match.group(1)) if gas_match else None)
    return tests


def declared_tests(package: str, package_dir: Path) -> dict[str, int | None]:
    """Full test name (`package::module::...::fn` for a unit test, `package_integrationtest::
    file_stem::module::...::fn` for an integration test — matching what snforge itself prints) ->
    its declared `l2_gas` budget, or None when the test has no `#[available_gas(...)]`. Attributes
    may appear before or after `#[test]`, in either order. Raises if a `.cairo` file under `src/`
    or `tests/` contains `#[test]` but this discovery never reached it (fix loop 2 decision C):
    such a file would otherwise produce no measurement and no declared row, silently exempting it
    from the gas budget rule."""
    tests: dict[str, int | None] = {}
    visited: set[Path] = set()

    def scan(prefix: tuple[str, ...], root_file: Path, root_dir: Path | None = None) -> None:
        nodes = module_nodes(root_file, root_dir)
        visited.update(file.resolve() for _, _, file in nodes)
        tests.update(tests_of_nodes(prefix, nodes))

    scan((package,), package_dir / "src" / "lib.cairo")
    for stem, root_file in integration_test_roots(package_dir):
        scan((f"{package}_integrationtest", stem), root_file, root_file.parent / stem)

    all_cairo = set((package_dir / "src").rglob("*.cairo"))
    tests_dir = package_dir / "tests"
    if tests_dir.is_dir():
        all_cairo |= set(tests_dir.rglob("*.cairo"))
    for file in sorted(all_cairo):
        if file.resolve() in visited:
            continue
        if "#[test]" in file.read_text():
            raise SystemExit(
                f"{file.resolve().relative_to(ROOT)}: contains #[test] but was not reached by "
                f"gas-test discovery (not declared by any `mod` reachable from src/lib.cairo, and "
                f"not a top-level file directly under tests/) — fix loop 2 decision C"
            )

    return tests


def run_snforge(package: str) -> str:
    cmd = ["snforge", "test", "-p", package, "--detailed-resources"]
    print("$", " ".join(cmd), file=sys.stderr)
    p = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    out = p.stdout + p.stderr
    if p.returncode not in (0, 1):  # 1: some test failed, still parseable
        sys.exit(f"snforge failed for {package}:\n" + "\n".join(out.splitlines()[-40:]))
    return out


FUZZ_MAX_RE = re.compile(r"l2_gas:\s*\{max:\s*~(\d+)")
IGNORE_RE = re.compile(r"^\[IGNORE\] (\S+)")
COLLECTED_RE = re.compile(r"^Collected (\d+) test\(s\)")


class Snforge:
    """What one `snforge test --detailed-resources` run printed: `ran` (every test reported PASS or
    FAIL -> passed), `measured` (name -> (gas, passed)), `ignored`, and `collected`.

    A plain test is measured by its `sierra gas: N` line. A fuzz test prints no such line: its
    result line reads `[PASS] name (runs: 256, (l1_gas: {max: ~0, ...}, l1_data_gas: {...},
    l2_gas: {max: ~186639, min: ~106432, mean: ~128053, std deviation: ~13553}))` (snforge 0.61.0,
    sample in scripts/tests/fixtures/), and its measurement is that `max` (the rules are held to the
    maximum over the runs)."""

    def __init__(self, ran, measured, ignored, collected):
        self.ran, self.measured, self.ignored, self.collected = ran, measured, ignored, collected


def parse_output(out: str) -> Snforge:
    ran: dict[str, bool] = {}
    measured: dict[str, tuple[int, bool]] = {}
    ignored: set[str] = set()
    collected = None
    current = None
    passed = True
    for line in out.splitlines():
        m = PASS_RE.match(line)
        if m:
            current = m.group(2)
            passed = m.group(1) == "PASS"
            ran[current] = passed
            fuzz = FUZZ_MAX_RE.search(line)
            if fuzz:
                measured[current] = (int(fuzz.group(1)), passed)
                current = None
            continue
        ig = IGNORE_RE.match(line)
        if ig:
            ignored.add(ig.group(1))
            continue
        c = COLLECTED_RE.match(line)
        if c:
            collected = int(c.group(1))
            continue
        if current is None:
            continue
        g = GAS_LINE_RE.match(line)
        if g:
            measured[current] = (int(g.group(1)), passed)
            current = None
    return Snforge(ran, measured, ignored, collected)


def parse_measurements(out: str) -> dict[str, tuple[int, bool]]:
    """Full test name (`pkg::mod::...::name`, exactly as snforge prints it) -> (measured gas,
    passed)."""
    return parse_output(out).measured


def collect() -> tuple[dict[str, dict[str, dict]], dict[str, dict]]:
    """(rows, infos). rows: package -> {full_test_name: {"measured": int|None, "declared":
    int|None, "passed": bool|None, "ran": bool, "ignored": bool}}; `measured` is None for a test
    snforge did not run (`#[ignore]`d, filtered out) and for a test it ran but printed no usable
    measurement for (`ran` is True: an error of `check`). infos: package -> {"collected": int|None,
    "declared": int}."""
    packages: dict[str, dict[str, dict]] = {}
    infos: dict[str, dict] = {}
    for package, package_dir in workspace_packages().items():
        declared = declared_tests(package, package_dir)
        out = parse_output(run_snforge(package))
        rows: dict[str, dict] = {}
        for full in sorted(set(declared) | set(out.ran) | out.ignored):
            gas_passed = out.measured.get(full)
            rows[full] = {
                "declared": declared.get(full),
                "measured": gas_passed[0] if gas_passed else None,
                "passed": gas_passed[1] if gas_passed else None,
                "ran": full in out.ran,
                "ignored": full in out.ignored,
                "is_declared": full in declared,
            }
        packages[package] = rows
        infos[package] = {"collected": out.collected, "declared": len(declared)}
    return packages, infos


def reconcile(packages: dict[str, dict[str, dict]], infos: dict[str, dict]) -> tuple[list[str], list[str]]:
    """(errors, count lines): tests declared in the sources = tests snforge collected; every test
    that ran has a gas row; every declared test without a row is ignored."""
    bad: list[str] = []
    lines: list[str] = []
    for package, rows in sorted(packages.items()):
        info = infos[package]
        with_row = sum(1 for r in rows.values() if r["ran"] and r["measured"] is not None)
        ignored = sum(1 for r in rows.values() if r["ignored"])
        lines.append(f"{package}: declared {info['declared']}, collected {info['collected']}, "
                     f"with a gas row {with_row}, ignored {ignored}")
        if info["collected"] != info["declared"]:
            bad.append(f"{package}: {info['declared']} tests declared in the sources but "
                       f"snforge collected {info['collected']}")
        for name, r in sorted(rows.items()):
            if not r.get("is_declared", True):
                bad.append(f"{name}: snforge reported it but discovery did not find it in the "
                           f"sources")
            elif r["ran"] and r["measured"] is None:
                bad.append(f"{name}: ran but no gas measurement could be parsed from the "
                           f"output of snforge")
            elif not r["ran"] and not r["ignored"]:
                bad.append(f"{name}: declared, but snforge neither ran nor ignored it")
    return bad, lines



INHERITED = GAS / "takeover-tests.txt"
INHERITED_HEADER = """\
# The tests taken over from origami_hexmap 1.8.0 (04ab30c): every `#[test]` of the moved files of
# scripts/takeover_check.py, under its module path in `hexx` (the source's, after the rewrites).
# Generated by `python3 scripts/bench.py baseline --inherited --source <crates/hexmap>`, never by
# hand, and verified against the source by the CI job `takeover` (`--check`). It is the only set
# gas/takeover-baseline.txt may draw from: `bench.py check` rejects any other entry.
"""
DEFAULT_SOURCE = ROOT / "sources" / "origami" / "crates" / "hexmap"
PACKAGE = "hexx"


def module_prefix(dst_rel: str) -> tuple[str, ...]:
    """Module path of a moved file, from its destination (`src/board/map.cairo` ->
    `hexx::board::map`, `tests/readme.cairo` -> `hexx_integrationtest::readme`)."""
    parts = Path(dst_rel).with_suffix("").parts
    if parts[0] == "tests":
        return (f"{PACKAGE}_integrationtest", *parts[1:])
    assert parts[0] == "src", dst_rel
    return (PACKAGE, *parts[1:])


def inherited_tests(source: Path) -> set[str]:
    """Every test of the pinned source that the take-over moved, under its name in `hexx`. The
    source files are those of scripts/takeover_check.py's table, after its rewrites (the removal of
    `u252` included); the names are derived from the destination path of each pair, and
    scripts/takeover_check.py proves that the destination is that file."""
    import takeover_check as tc

    names: set[str] = set()
    for src_rel, dst_rel in tc.table(source):
        if not src_rel.endswith(".cairo"):
            continue
        text = tc.rewritten(src_rel, (source / src_rel).read_text())
        nodes = module_nodes(source / src_rel, None, text)
        names.update(tests_of_nodes(module_prefix(dst_rel), nodes))
    return names


def read_inherited(path: Path = INHERITED) -> set[str] | None:
    return read_baseline(path)


def render_inherited(names: set[str]) -> str:
    return INHERITED_HEADER + "".join(f"{name}\n" for name in sorted(names))


def approved_inherited(source: Path | None, list_path: Path = INHERITED,
                       proof=None) -> tuple[set[str], str]:
    """The approved set a baseline entry must belong to, and where it came from. With the source
    (a checkout of the pinned commit): the tests of the moved files, after `proof` (default:
    scripts/takeover_check.py, which must find the 29 pairs `same`), and the committed list must
    agree with it. Without: the committed list gas/takeover-tests.txt, which CI verifies against
    the source."""
    committed = read_inherited(list_path)
    if source is not None and (source / "src" / "map.cairo").is_file():
        if proof is None:
            proof = takeover_proof
        proof(source)
        names = inherited_tests(source)
        if committed is not None and committed != names:
            raise SystemExit(
                f"{list_path.name} disagrees with the source ({len(committed - names)} not in the "
                f"source, {len(names - committed)} missing): regenerate it with `python3 "
                f"scripts/bench.py baseline --inherited --source {source}`")
        return names, f"the source {source}"
    if committed is None:
        raise SystemExit(f"no source checkout and no {list_path.name}: the inherited tests cannot "
                         f"be established")
    return committed, list_path.name


def takeover_proof(source: Path) -> None:
    """Fails unless scripts/takeover_check.py finds every pair `same` (the moved files)."""
    import io
    import takeover_check as tc

    out = io.StringIO()
    if tc.check(source, tc.DEST, out):
        raise SystemExit("scripts/takeover_check.py does not prove the move:\n" + out.getvalue())


def conformant(row: dict) -> bool:
    """Whether a test obeys the two rules an inherited test may break: it has a budget, and the
    budget is not above `ceil(1.05 * measured)` (unjudgeable, hence conformant, if not measured)."""
    if row["declared"] is None:
        return False
    if row["measured"] is None:
        return True
    return row["declared"] <= math.ceil(1.05 * row["measured"])


def nonconformant(packages: dict[str, dict[str, dict]]) -> set[str]:
    return {name for rows in packages.values() for name, row in rows.items()
            if not conformant(row)}


def read_baseline(path: Path = BASELINE) -> set[str] | None:
    """The test paths of the baseline; None when the file does not exist."""
    if not path.exists():
        return None
    return {line.strip() for line in path.read_text().splitlines()
            if line.strip() and not line.startswith("#")}


def render_baseline(names: set[str]) -> str:
    return BASELINE_HEADER + "".join(f"{name}\n" for name in sorted(names))


def baseline_update(existing: set[str] | None, packages: dict[str, dict[str, dict]],
                    allow_growth: bool = False,
                    approved: set[str] | None = None) -> tuple[set[str], list[str]]:
    """The new baseline and the tests it ADDS, which is an error unless `allow_growth`. A missing
    file is the bootstrap: every non-conformant test is the first baseline. Whatever the flag, a
    test outside `approved` (the inherited tests) is refused: `check` would reject it anyway."""
    new = nonconformant(packages)
    if approved is not None and new - approved:
        raise SystemExit("bench.py baseline refuses tests that are not inherited from the "
                         "take-over; make them conformant:\n  "
                         + "\n  ".join(sorted(new - approved)))
    growth = sorted(new - existing) if existing is not None else []
    if growth and not allow_growth:
        raise SystemExit("bench.py baseline refuses to add tests to the baseline (it only "
                         "shrinks); make them conformant:\n  " + "\n  ".join(growth))
    return new, growth


def budget_violations(packages: dict[str, dict[str, dict]],
                      baseline: set[str] | None = None,
                      approved: set[str] | None = None) -> list[str]:
    """`approved`, when given, is the set of inherited tests the baseline may hold (finding 3): an
    entry outside it is an error, so the baseline cannot grow by a manual edit."""
    baseline = baseline or set()
    bad = []
    known: set[str] = set()
    if approved is not None:
        for name in sorted(baseline - approved):
            bad.append(f"{name}: is in gas/takeover-baseline.txt but is not a test inherited from "
                       f"the take-over (gas/takeover-tests.txt): the baseline cannot hold it")
    for package, rows in packages.items():
        for name, row in sorted(rows.items()):
            known.add(name)
            inherited = name in baseline
            if inherited and conformant(row):
                bad.append(f"{name}: is in gas/takeover-baseline.txt but is conformant now: "
                           f"regenerate it with `python3 scripts/bench.py baseline`")
            if row["measured"] is None:
                if row.get("ran"):
                    bad.append(f"{name}: ran but no gas measurement could be parsed from the "
                               f"output of snforge")
                    continue
                if row["declared"] is None and not inherited:
                    bad.append(f"{name}: not measured (ignored or filtered) and no "
                               f"#[available_gas(l2_gas: ...)]")
                continue  # not measured but has a budget: cannot verify it, not a violation
            if row["passed"] is False:
                bad.append(f"{name}: test failed, cannot verify its gas budget")
                continue
            if row["declared"] is None:
                if not inherited:
                    bad.append(f"{name}: no #[available_gas(l2_gas: ...)]")
                continue
            measured, declared = row["measured"], row["declared"]
            ceiling = math.ceil(1.05 * measured)
            if declared > ceiling and not inherited:
                bad.append(f"{name}: budget {declared} is more than 5 % above its measurement "
                           f"{measured} (ceil(1.05x) = {ceiling})")
            elif declared < measured:
                bad.append(f"{name}: budget {declared} is below its measurement {measured}; "
                           f"the test would fail for lack of gas")
    for name in sorted(baseline - known):
        bad.append(f"{name}: is in gas/takeover-baseline.txt but does not exist any more: "
                   f"regenerate it with `python3 scripts/bench.py baseline`")
    return bad


def read_snapshots() -> dict[str, dict[str, int]]:
    snap = {}
    for path in sorted(GAS.glob("*.snap")):
        if path.name == "bytecode.size":
            continue
        for line in path.read_text().splitlines():
            if line.startswith("#") or not line.strip():
                continue
            name, vals = line.rsplit(":", 1)
            measured, budget = vals.split()
            snap[name] = {"measured": int(measured),
                          "declared": None if budget == "None" else int(budget)}
    return snap


def write_snapshots(packages: dict[str, dict[str, dict]]) -> None:
    GAS.mkdir(exist_ok=True)
    written = 0
    measured_packages = {
        package: {n: r for n, r in rows.items() if r["measured"] is not None}
        for package, rows in packages.items()
    }
    for existing in GAS.glob("*.snap"):
        if existing.stem not in measured_packages or not measured_packages[existing.stem]:
            existing.unlink()
    for package, rows in measured_packages.items():
        if not rows:
            continue
        lines = ["# gas: measured budget"]
        for name in sorted(rows):
            row = rows[name]
            lines.append(f"{name}: {row['measured']} {row['declared']}")
        (GAS / f"{package}.snap").write_text("\n".join(lines) + "\n")
        written += 1
    print(f"wrote {written} snapshot file(s) in gas/", file=sys.stderr)


def print_table(packages: dict[str, dict[str, dict]]) -> None:
    print("| test | measured (l2 gas) | budget | margin |\n|---|---:|---:|---:|")
    for rows in packages.values():
        for name in sorted(rows):
            row = rows[name]
            measured = row["measured"] if row["measured"] is not None else "—"
            budget = row["declared"] if row["declared"] is not None else "—"
            margin = (f"{100 * (row['declared'] / row['measured'] - 1):.1f} %"
                      if row["declared"] is not None and row["measured"] else "—")
            print(f"| `{name}` | {measured} | {budget} | {margin} |")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("cmd", choices=["run", "snapshot", "check", "baseline"])
    ap.add_argument("--allow-growth", action="store_true",
                    help="baseline only: allow the list to gain tests (no workflow uses it)")
    ap.add_argument("--inherited", action="store_true",
                    help="baseline only: (re)write gas/takeover-tests.txt from --source, no "
                         "measurement; with --check, verify the committed list instead")
    ap.add_argument("--check", action="store_true", help="with baseline --inherited: verify only")
    ap.add_argument("--source", type=Path, default=None,
                    help="crates/hexmap of the pinned checkout of dojoengine/origami "
                         f"(default: {DEFAULT_SOURCE.relative_to(ROOT)} when it exists)")
    args = ap.parse_args()
    source = args.source if args.source is not None else (
        DEFAULT_SOURCE if DEFAULT_SOURCE.is_dir() else None)

    if args.cmd == "baseline" and args.inherited:
        if source is None:
            sys.exit("baseline --inherited needs --source <crates/hexmap of the pinned checkout>")
        takeover_proof(source)
        names = inherited_tests(source)
        if args.check:
            committed = read_inherited()
            if committed != names:
                sys.exit(f"{INHERITED.relative_to(ROOT)} disagrees with the source: "
                         f"{len((committed or set()) - names)} not in the source, "
                         f"{len(names - (committed or set()))} missing")
            print(f"{INHERITED.relative_to(ROOT)} matches the source ({len(names)} tests)")
            return 0
        INHERITED.write_text(render_inherited(names))
        print(f"wrote {INHERITED.relative_to(ROOT)}: {len(names)} test(s)")
        return 0

    approved, provenance = approved_inherited(source)
    packages, infos = collect()
    print_table(packages)
    errors, counts = reconcile(packages, infos)
    print("\nreconciliation (declared in the sources / collected by snforge / with a gas row / "
          "ignored):", file=sys.stderr)
    for line in counts:
        print(f"  {line}", file=sys.stderr)

    if args.cmd == "snapshot":
        write_snapshots(packages)
        return 0
    if args.cmd == "baseline":
        new, growth = baseline_update(read_baseline(), packages, args.allow_growth, approved)
        BASELINE.write_text(render_baseline(new))
        print(f"wrote {BASELINE.relative_to(ROOT)}: {len(new)} test(s), {len(growth)} added",
              file=sys.stderr)
        return 0
    if args.cmd == "check":
        violations = errors + budget_violations(packages, read_baseline(), approved)
        if violations:
            print(f"\ngas budget violations (inherited tests from {provenance}):",
                  file=sys.stderr)
            for v in violations:
                print(f"  {v}", file=sys.stderr)
            return 1
        snap = read_snapshots()
        current = {
            name: {"measured": row["measured"], "declared": row["declared"]}
            for rows in packages.values() for name, row in rows.items()
            if row["measured"] is not None
        }
        bad = []
        for name in sorted(set(current) | set(snap)):
            new, old = current.get(name), snap.get(name)
            if old is None:
                bad.append(f"ADDED   {name}")
            elif new is None:
                bad.append(f"REMOVED {name}")
            elif new != old:
                bad.append(f"CHANGED {name}: {old} -> {new}")
        if bad:
            print("\n" + "\n".join(bad), file=sys.stderr)
            sys.exit("gas snapshot mismatch. Run `python3 scripts/bench.py snapshot` and commit gas/.")
        print(f"\ngas budgets and snapshot OK ({len(current)} tests)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
