#!/usr/bin/env python3
"""Generate docs/GAS.md from the committed gas snapshots (gas/*.snap).

A pure function of `gas/*.snap` and `.tool-versions`: no snforge run. `gas/*.snap` is the single
source of truth (`scripts/bench.py`, which measures and enforces the budget rule); this script
only renders it, mirroring the house `scripts/gas_tables.py` (`glam-cairo`) adapted to the
`origami_hexmap` per-test `#[available_gas]` form this package's tests use (see
`scripts/bench.py`'s module docstring and the LIB-04 report for why both forms coexist).

usage:
  scripts/gas_tables.py           rewrite docs/GAS.md
  scripts/gas_tables.py --check   exit 1 if docs/GAS.md is stale (CI and scripts/check.sh)
"""
from __future__ import annotations

import argparse
import difflib
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import bench  # noqa: E402  (the reader of the baseline of inherited tests)

ROOT = Path(__file__).resolve().parents[1]
GAS = ROOT / "gas"
OUTPUT = ROOT / "docs" / "GAS.md"


def toolchain() -> str:
    tools = []
    for line in (ROOT / ".tool-versions").read_text().splitlines():
        fields = line.split("#")[0].split()
        if len(fields) >= 2:
            tools.append(f"{fields[0]} {fields[1]}")
    return ", ".join(tools)


def read_snapshots() -> dict[str, dict[str, tuple[int, int | None]]]:
    packages: dict[str, dict[str, tuple[int, int | None]]] = {}
    for path in sorted(GAS.glob("*.snap")):
        if path.name == "bytecode.size":
            continue
        rows = {}
        for line in path.read_text().splitlines():
            if line.startswith("#") or not line.strip():
                continue
            name, vals = line.rsplit(":", 1)
            measured, budget = vals.split()
            rows[name] = (int(measured), None if budget == "None" else int(budget))
        packages[path.stem] = rows
    return packages


def render(packages: dict[str, dict[str, tuple[int, int | None]]],
           baseline: set[str] | None = None) -> str:
    baseline = baseline or set()
    lines = [
        "# Gas budgets",
        "",
        "Generated by `python3 scripts/gas_tables.py` from `gas/*.snap` (source of truth, written "
        "by `python3 scripts/bench.py snapshot`). Measured with " + toolchain() + " "
        "(`.tool-versions`), Sierra gas (`l2_gas`, what a transaction pays).",
        "",
        "The rule (COMMON.md §4, `grimworld:docs/CAIRO.md` §2): every `#[test]` carries "
        "`#[available_gas(l2_gas: N)]`; `N = ceil(1.05 * measured)` when a budget is set or "
        "raised, and lowering one needs nothing but the lower number. "
        "`python3 scripts/bench.py check` fails a test that was not measured (ignored, "
        "filtered) and has no budget, or whose budget is outside "
        "`[measured, ceil(1.05 * measured)]` (`scripts/check.sh`, CI job `gas`). The tests taken "
        "over unchanged from `origami_hexmap` 1.8.0 whose budget does not follow the rule are "
        "listed in `gas/takeover-baseline.txt` (it only shrinks; task M1-T1c empties it): they "
        "are exempt from those two rules and from nothing else, and are marked *inherited* "
        "below.",
        "",
        "| Test | Measured | Budget | Margin |",
        "|---|---:|---:|---:|",
    ]
    total_tests = 0
    for package in sorted(packages):
        for name in sorted(packages[package]):
            measured, budget = packages[package][name]
            total_tests += 1
            inherited = name in baseline
            if budget is None:
                shown = "none (inherited)" if inherited else "none"
                lines.append(f"| `{name}` | {measured:,} | {shown} | — |")
                continue
            margin = 100.0 * (budget / measured - 1.0) if measured else 0.0
            allowed = math.ceil(1.05 * measured)
            note = " (inherited)" if inherited else (
                "" if budget <= allowed else " (stale: exceeds the rule)")
            lines.append(f"| `{name}` | {measured:,} | {budget:,} | {margin:.1f} %{note} |")
    if total_tests == 0:
        lines.append("| _None yet_ | — | — | — |")
    inherited_count = sum(1 for rows in packages.values() for n in rows if n in baseline)
    lines += ["", f"{total_tests} measured test(s), {inherited_count} inherited "
                  f"(`gas/takeover-baseline.txt`)."]
    return "\n".join(lines) + "\n"


def write_or_check(generated: str, check: bool) -> int:
    current = OUTPUT.read_text() if OUTPUT.exists() else ""
    if check:
        if current == generated:
            print(f"{OUTPUT.relative_to(ROOT)} is up to date")
            return 0
        print(f"{OUTPUT.relative_to(ROOT)} is stale; run python3 scripts/gas_tables.py",
              file=sys.stderr)
        diff = difflib.unified_diff(current.splitlines(), generated.splitlines(),
                                    fromfile=str(OUTPUT), tofile="generated", lineterm="")
        for line in list(diff)[:80]:
            print(line, file=sys.stderr)
        return 1
    OUTPUT.write_text(generated)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if docs/GAS.md is stale")
    args = ap.parse_args()
    return write_or_check(render(read_snapshots(), bench.read_baseline()), args.check)


if __name__ == "__main__":
    raise SystemExit(main())
