//! N-6, range and ring as geometry (plan §6.7): the tiles of a board within a radius of a tile,
//! and those at exactly that radius, walls ignored, clipped to the board with its ring: the sight
//! of radius 6 and the area of an effect around a target.
//!
//! Two paths give the same result. Radius 0 is the tile itself, before any dispatch. The **table
//! path** serves the width 15 and a radius of `1..=7`: the canonical shape of `HEXAGONS` (or
//! `HEXAGON_RINGS`), clipped to the board **before** it is moved to the position (a move first
//! would reduce the bits that leave the board modulo the field), then one product. The **loop
//! path** serves every other case: one iteration per row of the board the shape meets, at most
//! `H`, each adding the row's extent (plan §6.7, "Dispatch").
//!
//! Mirrors nothing in `hexx`: an extension (plan §6.7, N-6). `hexx`'s `Hex::range` and `Hex::ring`
//! are the same sets on an unbounded grid; `tools/refgen` checks the tables against them.

// Internal imports

use hexx::board::asserter::Asserter;
use hexx::board::bits::Bits;
use hexx::board::map::HexMap;
use hexx::board::tables::{COL_FROM, ROW_FROM_16};

// Constants

/// The width the table path serves, and the same as a divisor.
const TABLE_WIDTH: u8 = 15;
const FIFTEEN: NonZero<u8> = 15;
/// The largest radius of the table path: a hexagon of radius `r` spans `2r + 1` columns.
const TABLE_RADIUS: u8 = 7;
/// 2, as a divisor.
const TWO: NonZero<u8> = 2;
/// The largest radius the loop path computes with: every distance on a board of the engine is
/// below `W + H ≤ 86` (`W · H ≤ 251`, `W, H ≥ 3`), so a larger radius has the same tiles
/// (all of them in `hexagon`, none in `hexagon_ring`), and `2r` stays in the tables of `Bits`.
const LOOP_RADIUS: u8 = 100;

// region generated by `cargo run --manifest-path tools/refgen/Cargo.toml -- gen hexagon`:
// tables, do not edit

/// The canonical hexagons of the table path, key `7 · (row is odd) + radius − 1`, radius
/// `1..=7`: the tiles of the 15 × 16 board within `radius` of `(7, 8)` (index 127, even row)
/// or `(7, 7)` (index 112, odd row). Each lies whole in the board.
const HEXAGONS: [felt252; 14] = [
    0x6001c0018000000000000000000000000000, 0x7000f003e003c007000000000000000000000000,
    0x3c00f801f807f007e00f800f00000000000000000000,
    0x3e007e01fc03fc0ff80ff01fc01f803e0000000000000000,
    0x1f807f00ff03fe07fe1ffc1ff83fe03fc07f007e000000000000,
    0x1fc03fc0ff81ff87ff0fff3ffe3ffc7ff07fe0ff80ff01fc00000000,
    0xff03fe07fe1ffc3ffcfff9fffffff7ffefff8fff1ffc1ff83fe03fc0000,
    0x180038006000000000000000000000000, 0xe003c007c00f000e00000000000000000000,
    0xf001f007e00fe01f801f003c0000000000000000, 0x7c01f803f80ff01ff03fc03f807e007c000000000000,
    0x7e00fe03fc07fc1ff83ff87fe07fc0ff00fe01f800000000,
    0x3f80ff01ff07fe0ffe3ffc7ffcfff0ffe1ff81ff03fc03f80000,
    0x3fc07fc1ff83ff8fff1fff7ffefffffff9fff3ffc3ff87fe07fc0ff0,
];
/// The canonical rings of the table path, the same keys: the tiles at exactly `radius`.
const HEXAGON_RINGS: [felt252; 14] = [
    0x600140018000000000000000000000000000, 0x7000900220024007000000000000000000000000,
    0x3c008801080410042008800f00000000000000000000,
    0x3e00420104020408080810104010803e0000000000000000,
    0x1f8041008102020402100410082020204041007e000000000000,
    0x1fc0204080810084010801200220044010402080808101fc00000000,
    0xff02020402100420048009000c001400280088011004100820203fc0000,
    0x180028006000000000000000000000000, 0xe00240044009000e00000000000000000000,
    0xf0011004200820108011003c0000000000000000, 0x7c01080208081010102040208042007c000000000000,
    0x7e008202040404100820084020404081008201f800000000,
    0x3f80810101040208022004400480108021008101020403f80000,
    0x3fc04041008200880110014002800300090012004200840204040ff0,
];

// endregion

/// A row of the loop path: the ends of the extent of the hexagon on it, the row, and its place in
/// the scan.
#[derive(Copy, Drop)]
struct Scan {
    /// `2^(row·W + lo)` and `2^(row·W + hi)`, the ends of the extent unclipped (an exponent below
    /// 0 is an inverse in the field, so that a move to the next row stays one exact product), and
    /// `2^(row·W)`.
    lo: felt252,
    hi: felt252,
    row: felt252,
    /// `|row − y|`, and whether the row lies above the centre.
    distance: felt252,
    above: bool,
    /// The parity of the row.
    odd: bool,
    /// Whether the extent leaves the row on the left (`lo < 0`) and on the right (`hi ≥ W`).
    left: bool,
    right: bool,
}

/// The constants of a scan.
#[derive(Copy, Drop)]
struct Bounds {
    /// `2^(W−1)`, `2^W`, `2^(W+1)`: the moves to the next row.
    narrow: felt252,
    width: felt252,
    wide: felt252,
    /// The extent leaves the row on the left when `|row − y| < left`, on the right when
    /// `|row − y| < right`: two bands about the row of the centre.
    left: felt252,
    right: felt252,
    /// `|row − y|` of the last row, below the centre.
    last: felt252,
}

#[generate_trait]
pub impl HexagonImpl of HexagonTrait {
    /// The tiles within a radius of a position, walls ignored.
    /// # Arguments
    /// * `self` - The map, any dimensions of the engine (`W, H >= 3`, `W * H <= 251`); they are
    ///   not checked: a map outside that domain is the caller's error, as in `LineTrait`
    /// * `position` - The centre, ring tiles included
    /// * `radius` - The radius, any
    /// # Returns
    /// * The bitmap of the tiles `t` of the board, ring included, with
    ///   `hex_distance(position, t) <= radius`; `2^position` for the radius 0
    /// # Panics
    /// * `'Asserter: position not inside'` if `position` is outside the board (`>= W * H`)
    ///
    /// Mirrors nothing in `hexx`: an extension (plan §6.7, N-6).
    fn hexagon(self: HexMap, position: u8, radius: u8) -> felt252 {
        // [Check] The position inside the board
        let (width, height) = (self.width, self.height);
        Asserter::assert_inside(width, height, position);
        // [Return] The radius 0, before any dispatch
        if radius == 0 {
            return Bits::pow(position);
        }
        // [Return] The table path: the width 15, a radius of at most 7
        if width == TABLE_WIDTH && radius <= TABLE_RADIUS {
            return HexagonInternal::table(HEXAGONS.span(), height, position, radius);
        }
        // [Return] The loop path
        HexagonInternal::rows(width, height, position, radius)
    }

    /// The tiles at exactly a radius of a position, walls ignored.
    /// # Arguments
    /// * `self` - The map, any dimensions of the engine (`W, H >= 3`, `W * H <= 251`); they are
    ///   not checked: a map outside that domain is the caller's error, as in `LineTrait`
    /// * `position` - The centre, ring tiles included
    /// * `radius` - The radius, any
    /// # Returns
    /// * The bitmap of the tiles `t` of the board, ring included, with
    ///   `hex_distance(position, t) == radius`, that is `hexagon(r) − hexagon(r − 1)`;
    ///   `2^position` for the radius 0
    /// # Panics
    /// * `'Asserter: position not inside'` if `position` is outside the board (`>= W * H`)
    ///
    /// Mirrors nothing in `hexx`: an extension (plan §6.7, N-6).
    fn hexagon_ring(self: HexMap, position: u8, radius: u8) -> felt252 {
        // [Check] The position inside the board
        let (width, height) = (self.width, self.height);
        Asserter::assert_inside(width, height, position);
        // [Return] The radius 0, before any dispatch
        if radius == 0 {
            return Bits::pow(position);
        }
        // [Return] The table path: the width 15, a radius of at most 7
        if width == TABLE_WIDTH && radius <= TABLE_RADIUS {
            return HexagonInternal::table(HEXAGON_RINGS.span(), height, position, radius);
        }
        // [Return] The loop path
        HexagonInternal::ring_rows(width, height, position, radius)
    }
}

#[generate_trait]
impl HexagonInternal of HexagonInternalTrait {
    /// The table path, on the width 15.
    /// # Arguments
    /// * `shapes` - `HEXAGONS` or `HEXAGON_RINGS`
    /// * `height` - The height of the map, at most 16
    /// * `position` - The centre, inside the board
    /// * `radius` - The radius, in `1..=7`
    /// # Returns
    /// * The canonical shape of the parity of the row, clipped to the board, then moved to
    ///   `position`
    #[inline(always)]
    fn table(shapes: Span<felt252>, height: u8, position: u8, radius: u8) -> felt252 {
        // [Compute] The canonical shape and its move: centre `(7, 8)`, index 127, on an even row,
        // `(7, 7)`, index 112, on an odd one; the row parity is kept by a move of whole row pairs
        let (y, x) = DivRem::div_rem(position, FIFTEEN);
        let (_, odd) = DivRem::div_rem(y, TWO);
        let shape = *shapes.at((TABLE_RADIUS * odd + radius - 1).into());
        let centre = 127 - TABLE_WIDTH * odd;
        let shift = if position >= centre {
            Bits::pow(position - centre)
        } else {
            Bits::inv(centre - position)
        };
        // [Return] The shape whole in the board: its columns are `x − r..=x + r`, its rows
        // `y − r..=y + r`
        if x >= radius && x + radius < TABLE_WIDTH && y >= radius && y + radius < height {
            return shape * shift;
        }
        // [Compute] The clip, in the canonical frame: the columns `[lo_c, hi_c)` and the rows
        // `[lo_r, hi_r)` that land in the board, with `lo_c = max(0, 7 − x)`,
        // `hi_c = min(15, 22 − x)`, `lo_r = max(0, y0 − y)`, `hi_r = min(16, y0 − y + H)`,
        // `y0`
        // the canonical row
        let row = 8 - odd;
        let lo_c = if x < 7 {
            7 - x
        } else {
            0
        };
        let hi_c = if x > 7 {
            22 - x
        } else {
            15
        };
        let lo_r = if y < row {
            row - y
        } else {
            0
        };
        let top = row + height - y;
        let hi_r = if top > 16 {
            16
        } else {
            top
        };
        // [Compute] The rectangle, the product of a column band and a row band (disjoint bits)
        let columns = *COL_FROM.span().at(lo_c.into()) - *COL_FROM.span().at(hi_c.into());
        let rows = *ROW_FROM_16.span().at(lo_r.into()) - *ROW_FROM_16.span().at(hi_r.into());
        let clipped = Bits::to_felt(Bits::and(shape.into(), (columns * rows).into()));
        // [Return] The move, exact: every bit left lands in the board, on its own row
        clipped * shift
    }

    /// The loop path of `hexagon`: each row of the board the hexagon meets adds its extent,
    /// clipped to the row.
    /// # Arguments
    /// * `width` - The width of the map
    /// * `height` - The height of the map
    /// * `position` - The centre, inside the board
    /// * `radius` - The radius, at least 1
    /// # Returns
    /// * The hexagon
    fn rows(width: u8, height: u8, position: u8, radius: u8) -> felt252 {
        let (mut scan, bounds, _) = ScanTrait::new(width, height, position, radius);
        let mut mask: felt252 = 0;
        loop {
            mask += scan.extent(@bounds);
            if !scan.above && scan.distance == bounds.last {
                break;
            }
            scan.step(@bounds);
        }
        mask
    }

    /// The loop path of `hexagon_ring`: on the rows at the distance `radius`, the whole extent;
    /// on every other row, its two ends (the extent of the radius `r − 1` is `lo + 1..=hi − 1`
    /// there), each when it lies in the row.
    /// # Arguments
    /// * `width` - The width of the map
    /// * `height` - The height of the map
    /// * `position` - The centre, inside the board
    /// * `radius` - The radius, at least 1
    /// # Returns
    /// * The ring
    fn ring_rows(width: u8, height: u8, position: u8, radius: u8) -> felt252 {
        let (mut scan, bounds, radius) = ScanTrait::new(width, height, position, radius);
        let mut mask: felt252 = 0;
        loop {
            if scan.distance == radius {
                mask += scan.extent(@bounds);
            } else {
                // [Compute] Both ends, distinct (the extent has at least `radius + 2` tiles)
                if !scan.left {
                    mask += scan.lo;
                }
                if !scan.right {
                    mask += scan.hi;
                }
            }
            if !scan.above && scan.distance == bounds.last {
                break;
            }
            scan.step(@bounds);
        }
        mask
    }
}

#[generate_trait]
impl ScanImpl of ScanTrait {
    /// The first row the hexagon meets and the constants of the scan.
    /// # Arguments
    /// * `width` - The width of the map
    /// * `height` - The height of the map
    /// * `position` - The centre `(x, y)`, inside the board
    /// * `radius` - The radius, at least 1
    /// # Returns
    /// * The scan on the row `max(0, y − r)`, its bounds (the last row is `min(H − 1, y + r)`),
    ///   and the radius the scan uses, `min(r, LOOP_RADIUS)`
    ///
    /// On the row at `k = |row − y|` the extent is `lo = x − r + A`, `hi = x + r − B` with
    /// `B = ⌈k/2⌉` and `A = ⌊k/2⌋` when `y` is even, the other way round when it is odd
    /// (odd-r offset, the same above and below the centre). It always holds the column `x`.
    /// So the extent leaves the row on the left iff `A < r − x`, that is
    /// `k < 2(r − x) − (y mod 2)`, and on the right iff `B < x + r + 1 − W`, that is
    /// `k < 2(x + r + 1 − W) − 1 + (y mod 2)`.
    #[inline(always)]
    fn new(width: u8, height: u8, position: u8, radius: u8) -> (Scan, Bounds, felt252) {
        let radius = if radius > LOOP_RADIUS {
            LOOP_RADIUS
        } else {
            radius
        };
        let (y, x) = DivRem::div_rem(position, width.try_into().unwrap());
        let (_, odd) = DivRem::div_rem(y, TWO);
        let top = if y > radius {
            radius
        } else {
            y
        };
        let below = height - 1 - y;
        let last = if radius < below {
            radius
        } else {
            below
        };
        // [Compute] The ends on the first row, `k = top`, as bit indices: `hi = first + r − B`,
        // `lo = hi − (2r − k)`
        let (shrink, _) = DivRem::div_rem(top + 1 - odd, TWO);
        let first = position - top * width;
        let hi = Bits::pow(first) * Bits::pow(radius - shrink);
        let lo = hi * Bits::inv(2 * radius - top);
        let row = Bits::pow(first - x);
        let (_, first_odd) = DivRem::div_rem(y - top, TWO);
        let narrow = Bits::pow(width - 1);
        // [Compute] The bands
        let (x, radius, width, odd): (u16, u16, u16, u16) = (
            x.into(), radius.into(), width.into(), odd.into(),
        );
        let left = if radius > x {
            2 * (radius - x) - odd
        } else {
            0
        };
        let span = x + radius + 1;
        let right = if span > width {
            2 * (span - width) - 1 + odd
        } else {
            0
        };
        // [Compute] The scan, its counters on `felt252` (equalities only, no range check)
        let distance: u16 = top.into();
        let scan = Scan {
            lo,
            hi,
            row,
            distance: distance.into(),
            above: top != 0,
            odd: first_odd == 1,
            left: distance < left,
            right: distance < right,
        };
        let bounds = Bounds {
            narrow,
            width: narrow + narrow,
            wide: 4 * narrow,
            left: left.into(),
            right: right.into(),
            last: last.into(),
        };
        (scan, bounds, radius.into())
    }

    /// The extent of the row, clipped to it.
    #[inline(always)]
    fn extent(self: @Scan, bounds: @Bounds) -> felt252 {
        let start = if *self.left {
            *self.row
        } else {
            *self.lo
        };
        let end = if *self.right {
            *self.row * *bounds.width
        } else {
            *self.hi + *self.hi
        };
        end - start
    }

    /// The next row: above the centre the extent grows by one tile, on the left from an even row
    /// and on the right from an odd one (odd-r offset); from the centre on it shrinks, on the right
    /// from an even row and on the left from an odd one. The clip of a side starts when `|row −
    /// y|`
    /// enters its band and ends when it leaves it.
    #[inline(always)]
    fn step(ref self: Scan, bounds: @Bounds) {
        let (narrow, width, wide) = (*bounds.narrow, *bounds.width, *bounds.wide);
        if self.above {
            if self.odd {
                self.lo *= width;
                self.hi *= wide;
            } else {
                self.lo *= narrow;
                self.hi *= width;
            }
            if self.distance == *bounds.left {
                self.left = true;
            }
            if self.distance == *bounds.right {
                self.right = true;
            }
            self.distance -= 1;
            self.above = self.distance != 0;
        } else {
            if self.odd {
                self.lo *= wide;
                self.hi *= width;
            } else {
                self.lo *= width;
                self.hi *= narrow;
            }
            self.distance += 1;
            if self.distance == *bounds.left {
                self.left = false;
            }
            if self.distance == *bounds.right {
                self.right = false;
            }
        }
        self.row *= width;
        self.odd = !self.odd;
    }
}

#[cfg(test)]
mod tests {
    // Core imports

    use core::dict::Felt252Dict;

    // Local imports

    use hexx::board::asserter::Asserter;
    use hexx::board::bits::Bits;
    use hexx::board::layout::LayoutTrait;
    use hexx::board::map::{HexMap, HexMapTrait};
    use hexx::finders::bfs::Bfs;
    use super::{HEXAGONS, HEXAGON_RINGS, HexagonInternal, HexagonTrait};

    /// The window of the game.
    const WIDTH: u8 = 15;
    const HEIGHT: u8 = 16;

    // region generated by `cargo run --manifest-path tools/refgen/Cargo.toml -- gen hexagon`:
    // sights, do not edit

    /// The per-position variant of plan §6.7 ("Why not the flood"), not shipped: the
    /// hexagon of radius 6 of every position of 15 × 16, clipped to the board.
    const SIGHTS: [felt252; 240] = [
        0x3c007801f003e00fc01f807f, 0x7c00f803f007e01fc03f80ff, 0xfc01f807f00fe03fc07f81ff,
        0x1fc03f80ff01fe07fc0ff83ff, 0x3f807f81ff03fe0ffc1ff87ff, 0x7f00ff03fe07fe1ffc3ff8fff,
        0xfe01fe07fc0ffc3ff87ff9fff, 0x1fc03fc0ff81ff87ff0fff3ffe, 0x3f807f81ff03ff0ffe1ffe7ffc,
        0x7f00ff03fe07fe1ffc3ffc7ff8, 0xfe01fe07fc0ffc1ff83ff87ff0, 0x1fc03fc07f80ff81ff03ff07fe0,
        0x1f803f807f00ff01fe03fe07fc0, 0x1f003f007e00fe01fc03fc07f80, 0x1e003e007c00fc01f803f807f00,
        0x1e007c00f803f007e01fc03f807f, 0x3e00fc01f807f00fe03fc07f80ff,
        0x7e01fc03f80ff01fe07fc0ff81ff, 0xfe03fc07f81ff03fe0ffc1ff83ff,
        0x1fc07f80ff83ff07fe1ffc3ff87ff, 0x3f80ff01ff07fe0ffe3ffc7ff8fff,
        0x7f01fe03fe0ffc1ffc7ff8fff9ffe, 0xfe03fc07fc1ff83ff8fff1fff3ffc,
        0x1fc07f80ff83ff07ff1ffe3ffe7ff8, 0x3f80ff01ff07fe0ffe1ffc3ffc7ff0,
        0x7f01fe03fe07fc0ffc1ff83ff87fe0, 0xfe01fc03fc07f80ff81ff03ff07fc0,
        0xfc01f803f807f00ff01fe03fe07f80, 0xf801f003f007e00fe01fc03fc07f00,
        0xf001e003e007c00fc01f803f807e00, 0xf001e007c00f803f007e01fc01f803f,
        0x1f003e00fc01f807f00fe03fc03f807f, 0x3f007e01fc03f80ff01fe07fc07f80ff,
        0x7f00fe03fc07f81ff03fe0ffc0ff81ff, 0xfe01fe07fc0ff83ff07fe1ffc1ff83ff,
        0x1fc03fc0ff81ff87ff0ffe3ffc3ff87ff, 0x3f807f81ff03ff0ffe1ffe7ffc7ff8ffe,
        0x7f00ff03fe07fe1ffc3ffcfff8fff1ffc, 0xfe01fe07fc0ffc3ff87ff9fff1ffe3ff8,
        0x1fc03fc0ff81ff87ff0fff1ffe3ffc7ff0, 0x3f807f81ff03ff07fe0ffe1ffc3ff87fe0,
        0x7f00ff01fe03fe07fc0ffc1ff83ff07fc0, 0x7e00fe01fc03fc07f80ff81ff03fe07f80,
        0x7c00fc01f803f807f00ff01fe03fc07f00, 0x7800f801f003f007e00fe01fc03f807e00,
        0x7801f003e00fc01f807f00fe01fc01f803f, 0xf803f007e01fc03f80ff01fe03fc03f807f,
        0x1f807f00fe03fc07f81ff03fe07fc07f80ff, 0x3f80ff01fe07fc0ff83ff07fe0ffc0ff81ff,
        0x7f01fe03fe0ffc1ff87ff0ffe1ffc1ff83ff, 0xfe03fc07fc1ff83ff8fff1ffe3ffc3ff87fe,
        0x1fc07f80ff83ff07ff1ffe3ffe7ff87ff0ffc, 0x3f80ff01ff07fe0ffe3ffc7ffcfff0ffe1ff8,
        0x7f01fe03fe0ffc1ffc7ff8fff9ffe1ffc3ff0, 0xfe03fc07fc1ff83ff87ff0fff1ffc3ff87fe0,
        0x1fc07f80ff81ff03ff07fe0ffe1ff83ff07fc0, 0x3f807f00ff01fe03fe07fc0ffc1ff03fe07f80,
        0x3f007e00fe01fc03fc07f80ff81fe03fc07f00, 0x3e007c00fc01f803f807f00ff01fc03f807e00,
        0x3c007800f801f003f007e00fe01f803f007c00, 0x3c007801f003e00fc01f807f007e00fc00f801f,
        0x7c00f803f007e01fc03f80ff00fe01fc01f803f, 0xfc01f807f00fe03fc07f81ff01fe03fc03f807f,
        0x1fc03f80ff01fe07fc0ff83ff03fe07fc07f80ff, 0x3f807f81ff03fe0ffc1ff87ff07fe0ffc0ff81ff,
        0x7f00ff03fe07fe1ffc3ff8fff0ffe1ffc1ff83fe, 0xfe01fe07fc0ffc3ff87ff9fff1ffe3ff83ff07fc,
        0x1fc03fc0ff81ff87ff0fff3ffe3ffc7ff07fe0ff8, 0x3f807f81ff03ff0ffe1ffe7ffc7ff8ffe0ffc1ff0,
        0x7f00ff03fe07fe1ffc3ffc7ff8fff1ffc1ff83fe0, 0xfe01fe07fc0ffc1ff83ff87ff0ffe1ff83ff07fc0,
        0x1fc03fc07f80ff81ff03ff07fe0ffc1ff03fe07f80, 0x1f803f807f00ff01fe03fe07fc0ff81fe03fc07f00,
        0x1f003f007e00fe01fc03fc07f80ff01fc03f807e00, 0x1e003e007c00fc01f803f807f00fe01f803f007c00,
        0x1e007c00f803f007e01fc03f807f007e00fc00f801f,
        0x3e00fc01f807f00fe03fc07f80ff00fe01fc01f803f,
        0x7e01fc03f80ff01fe07fc0ff81ff01fe03fc03f807f,
        0xfe03fc07f81ff03fe0ffc1ff83ff03fe07fc07f80ff,
        0x1fc07f80ff83ff07fe1ffc3ff87ff07fe0ffc0ff81fe,
        0x3f80ff01ff07fe0ffe3ffc7ff8fff0ffe1ff81ff03fc,
        0x7f01fe03fe0ffc1ffc7ff8fff9ffe1ffc3ff03fe07f8,
        0xfe03fc07fc1ff83ff8fff1fff3ffc3ff87fe07fc0ff0,
        0x1fc07f80ff83ff07ff1ffe3ffe7ff87ff0ffc0ff81fe0,
        0x3f80ff01ff07fe0ffe1ffc3ffc7ff0ffe1ff81ff03fc0,
        0x7f01fe03fe07fc0ffc1ff83ff87fe0ffc1ff03fe07f80,
        0xfe01fc03fc07f80ff81ff03ff07fc0ff81fe03fc07f00,
        0xfc01f803f807f00ff01fe03fe07f80ff01fc03f807e00,
        0xf801f003f007e00fe01fc03fc07f00fe01f803f007c00,
        0xf001e003e007c00fc01f803f807e00fc01f003e007800,
        0xf001e007c00f803f007e01fc01f803f003e007c007800f,
        0x1f003e00fc01f807f00fe03fc03f807f007e00fc00f801f,
        0x3f007e01fc03f80ff01fe07fc07f80ff00fe01fc01f803f,
        0x7f00fe03fc07f81ff03fe0ffc0ff81ff01fe03fc03f807f,
        0xfe01fe07fc0ff83ff07fe1ffc1ff83ff03fe07fc07f80fe,
        0x1fc03fc0ff81ff87ff0ffe3ffc3ff87ff07fe0ff80ff01fc,
        0x3f807f81ff03ff0ffe1ffe7ffc7ff8ffe0ffc1ff01fe03f8,
        0x7f00ff03fe07fe1ffc3ffcfff8fff1ffc1ff83fe03fc07f0,
        0xfe01fe07fc0ffc3ff87ff9fff1ffe3ff83ff07fc07f80fe0,
        0x1fc03fc0ff81ff87ff0fff1ffe3ffc7ff07fe0ff80ff01fc0,
        0x3f807f81ff03ff07fe0ffe1ffc3ff87fe0ffc1ff01fe03f80,
        0x7f00ff01fe03fe07fc0ffc1ff83ff07fc0ff81fe03fc07f00,
        0x7e00fe01fc03fc07f80ff81ff03fe07f80ff01fc03f807e00,
        0x7c00fc01f803f807f00ff01fe03fc07f00fe01f803f007c00,
        0x7800f801f003f007e00fe01fc03f807e00fc01f003e007800,
        0x7801f003e00fc01f807f00fe01fc01f803f003e007c0078000,
        0xf803f007e01fc03f80ff01fe03fc03f807f007e00fc00f8000,
        0x1f807f00fe03fc07f81ff03fe07fc07f80ff00fe01fc01f8000,
        0x3f80ff01fe07fc0ff83ff07fe0ffc0ff81ff01fe03fc03f8000,
        0x7f01fe03fe0ffc1ff87ff0ffe1ffc1ff83ff03fe07f807f0000,
        0xfe03fc07fc1ff83ff8fff1ffe3ffc3ff87fe07fc0ff00fe0000,
        0x1fc07f80ff83ff07ff1ffe3ffe7ff87ff0ffc0ff81fe01fc0000,
        0x3f80ff01ff07fe0ffe3ffc7ffcfff0ffe1ff81ff03fc03f80000,
        0x7f01fe03fe0ffc1ffc7ff8fff9ffe1ffc3ff03fe07f807f00000,
        0xfe03fc07fc1ff83ff87ff0fff1ffc3ff87fe07fc0ff00fe00000,
        0x1fc07f80ff81ff03ff07fe0ffe1ff83ff07fc0ff81fe01fc00000,
        0x3f807f00ff01fe03fe07fc0ffc1ff03fe07f80ff01fc03f800000,
        0x3f007e00fe01fc03fc07f80ff81fe03fc07f00fe01f803f000000,
        0x3e007c00fc01f803f807f00ff01fc03f807e00fc01f003e000000,
        0x3c007800f801f003f007e00fe01f803f007c00f801e003c000000,
        0x3c007801f003e00fc01f807f007e00fc00f801f001e003c0000000,
        0x7c00f803f007e01fc03f80ff00fe01fc01f803f003e007c0000000,
        0xfc01f807f00fe03fc07f81ff01fe03fc03f807f007e00fc0000000,
        0x1fc03f80ff01fe07fc0ff83ff03fe07fc07f80ff00fe01fc0000000,
        0x3f807f81ff03fe0ffc1ff87ff07fe0ffc0ff81ff01fe03f80000000,
        0x7f00ff03fe07fe1ffc3ff8fff0ffe1ffc1ff83fe03fc07f00000000,
        0xfe01fe07fc0ffc3ff87ff9fff1ffe3ff83ff07fc07f80fe00000000,
        0x1fc03fc0ff81ff87ff0fff3ffe3ffc7ff07fe0ff80ff01fc00000000,
        0x3f807f81ff03ff0ffe1ffe7ffc7ff8ffe0ffc1ff01fe03f800000000,
        0x7f00ff03fe07fe1ffc3ffc7ff8fff1ffc1ff83fe03fc07f000000000,
        0xfe01fe07fc0ffc1ff83ff87ff0ffe1ff83ff07fc07f80fe000000000,
        0x1fc03fc07f80ff81ff03ff07fe0ffc1ff03fe07f80ff01fc000000000,
        0x1f803f807f00ff01fe03fe07fc0ff81fe03fc07f00fe01f8000000000,
        0x1f003f007e00fe01fc03fc07f80ff01fc03f807e00fc01f0000000000,
        0x1e003e007c00fc01f803f807f00fe01f803f007c00f801e0000000000,
        0x1e007c00f803f007e01fc03f807f007e00fc00f801f001e00000000000,
        0x3e00fc01f807f00fe03fc07f80ff00fe01fc01f803f003e00000000000,
        0x7e01fc03f80ff01fe07fc0ff81ff01fe03fc03f807f007e00000000000,
        0xfe03fc07f81ff03fe0ffc1ff83ff03fe07fc07f80ff00fe00000000000,
        0x1fc07f80ff83ff07fe1ffc3ff87ff07fe0ffc0ff81fe01fc00000000000,
        0x3f80ff01ff07fe0ffe3ffc7ff8fff0ffe1ff81ff03fc03f800000000000,
        0x7f01fe03fe0ffc1ffc7ff8fff9ffe1ffc3ff03fe07f807f000000000000,
        0xfe03fc07fc1ff83ff8fff1fff3ffc3ff87fe07fc0ff00fe000000000000,
        0x1fc07f80ff83ff07ff1ffe3ffe7ff87ff0ffc0ff81fe01fc000000000000,
        0x3f80ff01ff07fe0ffe1ffc3ffc7ff0ffe1ff81ff03fc03f8000000000000,
        0x7f01fe03fe07fc0ffc1ff83ff87fe0ffc1ff03fe07f807f0000000000000,
        0xfe01fc03fc07f80ff81ff03ff07fc0ff81fe03fc07f00fe0000000000000,
        0xfc01f803f807f00ff01fe03fe07f80ff01fc03f807e00fc0000000000000,
        0xf801f003f007e00fe01fc03fc07f00fe01f803f007c00f80000000000000,
        0xf001e003e007c00fc01f803f807e00fc01f003e007800f00000000000000,
        0x1e007c00f803f007e01fc01f803f003e007c007800f000000000000000,
        0x3e00fc01f807f00fe03fc03f807f007e00fc00f801f000000000000000,
        0x7e01fc03f80ff01fe07fc07f80ff00fe01fc01f803f000000000000000,
        0xfe03fc07f81ff03fe0ffc0ff81ff01fe03fc03f807f000000000000000,
        0x1fe07fc0ff83ff07fe1ffc1ff83ff03fe07fc07f80fe000000000000000,
        0x3fc0ff81ff87ff0ffe3ffc3ff87ff07fe0ff80ff01fc000000000000000,
        0x7f81ff03ff0ffe1ffe7ffc7ff8ffe0ffc1ff01fe03f8000000000000000,
        0xff03fe07fe1ffc3ffcfff8fff1ffc1ff83fe03fc07f0000000000000000,
        0x1fe07fc0ffc3ff87ff9fff1ffe3ff83ff07fc07f80fe0000000000000000,
        0x3fc0ff81ff87ff0fff1ffe3ffc7ff07fe0ff80ff01fc0000000000000000,
        0x7f81ff03ff07fe0ffe1ffc3ff87fe0ffc1ff01fe03f80000000000000000,
        0xff01fe03fe07fc0ffc1ff83ff07fc0ff81fe03fc07f00000000000000000,
        0xfe01fc03fc07f80ff81ff03fe07f80ff01fc03f807e00000000000000000,
        0xfc01f803f807f00ff01fe03fc07f00fe01f803f007c00000000000000000,
        0xf801f003f007e00fe01fc03f807e00fc01f003e007800000000000000000,
        0x3e00fc01f807f00fe01fc01f803f003e007c0078000000000000000000,
        0x7e01fc03f80ff01fe03fc03f807f007e00fc00f8000000000000000000,
        0xfe03fc07f81ff03fe07fc07f80ff00fe01fc01f8000000000000000000,
        0x1fe07fc0ff83ff07fe0ffc0ff81ff01fe03fc03f8000000000000000000,
        0x3fe0ffc1ff87ff0ffe1ffc1ff83ff03fe07f807f0000000000000000000,
        0x7fc1ff83ff8fff1ffe3ffc3ff87fe07fc0ff00fe0000000000000000000,
        0xff83ff07ff1ffe3ffe7ff87ff0ffc0ff81fe01fc0000000000000000000,
        0x1ff07fe0ffe3ffc7ffcfff0ffe1ff81ff03fc03f80000000000000000000,
        0x3fe0ffc1ffc7ff8fff9ffe1ffc3ff03fe07f807f00000000000000000000,
        0x7fc1ff83ff87ff0fff1ffc3ff87fe07fc0ff00fe00000000000000000000,
        0xff81ff03ff07fe0ffe1ff83ff07fc0ff81fe01fc00000000000000000000,
        0xff01fe03fe07fc0ffc1ff03fe07f80ff01fc03f800000000000000000000,
        0xfe01fc03fc07f80ff81fe03fc07f00fe01f803f000000000000000000000,
        0xfc01f803f807f00ff01fc03f807e00fc01f003e000000000000000000000,
        0xf801f003f007e00fe01f803f007c00f801e003c000000000000000000000,
        0x3e00fc01f807f007e00fc00f801f001e003c0000000000000000000000,
        0x7e01fc03f80ff00fe01fc01f803f003e007c0000000000000000000000,
        0xfe03fc07f81ff01fe03fc03f807f007e00fc0000000000000000000000,
        0x1fe07fc0ff83ff03fe07fc07f80ff00fe01fc0000000000000000000000,
        0x3fe0ffc1ff87ff07fe0ffc0ff81ff01fe03f80000000000000000000000,
        0x7fe1ffc3ff8fff0ffe1ffc1ff83fe03fc07f00000000000000000000000,
        0xffc3ff87ff9fff1ffe3ff83ff07fc07f80fe00000000000000000000000,
        0x1ff87ff0fff3ffe3ffc7ff07fe0ff80ff01fc00000000000000000000000,
        0x3ff0ffe1ffe7ffc7ff8ffe0ffc1ff01fe03f800000000000000000000000,
        0x7fe1ffc3ffc7ff8fff1ffc1ff83fe03fc07f000000000000000000000000,
        0xffc1ff83ff87ff0ffe1ff83ff07fc07f80fe000000000000000000000000,
        0xff81ff03ff07fe0ffc1ff03fe07f80ff01fc000000000000000000000000,
        0xff01fe03fe07fc0ff81fe03fc07f00fe01f8000000000000000000000000,
        0xfe01fc03fc07f80ff01fc03f807e00fc01f0000000000000000000000000,
        0xfc01f803f807f00fe01f803f007c00f801e0000000000000000000000000,
        0x7e01fc03f807f007e00fc00f801f001e00000000000000000000000000,
        0xfe03fc07f80ff00fe01fc01f803f003e00000000000000000000000000,
        0x1fe07fc0ff81ff01fe03fc03f807f007e00000000000000000000000000,
        0x3fe0ffc1ff83ff03fe07fc07f80ff00fe00000000000000000000000000,
        0x7fe1ffc3ff87ff07fe0ffc0ff81fe01fc00000000000000000000000000,
        0xffe3ffc7ff8fff0ffe1ff81ff03fc03f800000000000000000000000000,
        0x1ffc7ff8fff9ffe1ffc3ff03fe07f807f000000000000000000000000000,
        0x3ff8fff1fff3ffc3ff87fe07fc0ff00fe000000000000000000000000000,
        0x7ff1ffe3ffe7ff87ff0ffc0ff81fe01fc000000000000000000000000000,
        0xffe1ffc3ffc7ff0ffe1ff81ff03fc03f8000000000000000000000000000,
        0xffc1ff83ff87fe0ffc1ff03fe07f807f0000000000000000000000000000,
        0xff81ff03ff07fc0ff81fe03fc07f00fe0000000000000000000000000000,
        0xff01fe03fe07f80ff01fc03f807e00fc0000000000000000000000000000,
        0xfe01fc03fc07f00fe01f803f007c00f80000000000000000000000000000,
        0xfc01f803f807e00fc01f003e007800f00000000000000000000000000000,
        0x7e01fc01f803f003e007c007800f000000000000000000000000000000,
        0xfe03fc03f807f007e00fc00f801f000000000000000000000000000000,
        0x1fe07fc07f80ff00fe01fc01f803f000000000000000000000000000000,
        0x3fe0ffc0ff81ff01fe03fc03f807f000000000000000000000000000000,
        0x7fe1ffc1ff83ff03fe07fc07f80fe000000000000000000000000000000,
        0xffe3ffc3ff87ff07fe0ff80ff01fc000000000000000000000000000000,
        0x1ffe7ffc7ff8ffe0ffc1ff01fe03f8000000000000000000000000000000,
        0x3ffcfff8fff1ffc1ff83fe03fc07f0000000000000000000000000000000,
        0x7ff9fff1ffe3ff83ff07fc07f80fe0000000000000000000000000000000,
        0xfff1ffe3ffc7ff07fe0ff80ff01fc0000000000000000000000000000000,
        0xffe1ffc3ff87fe0ffc1ff01fe03f80000000000000000000000000000000,
        0xffc1ff83ff07fc0ff81fe03fc07f00000000000000000000000000000000,
        0xff81ff03fe07f80ff01fc03f807e00000000000000000000000000000000,
        0xff01fe03fc07f00fe01f803f007c00000000000000000000000000000000,
        0xfe01fc03f807e00fc01f003e007800000000000000000000000000000000,
        0xfe01fc01f803f003e007c0078000000000000000000000000000000000,
        0x1fe03fc03f807f007e00fc00f8000000000000000000000000000000000,
        0x3fe07fc07f80ff00fe01fc01f8000000000000000000000000000000000,
        0x7fe0ffc0ff81ff01fe03fc03f8000000000000000000000000000000000,
        0xffe1ffc1ff83ff03fe07f807f0000000000000000000000000000000000,
        0x1ffe3ffc3ff87fe07fc0ff00fe0000000000000000000000000000000000,
        0x3ffe7ff87ff0ffc0ff81fe01fc0000000000000000000000000000000000,
        0x7ffcfff0ffe1ff81ff03fc03f80000000000000000000000000000000000,
        0xfff9ffe1ffc3ff03fe07f807f00000000000000000000000000000000000,
        0xfff1ffc3ff87fe07fc0ff00fe00000000000000000000000000000000000,
        0xffe1ff83ff07fc0ff81fe01fc00000000000000000000000000000000000,
        0xffc1ff03fe07f80ff01fc03f800000000000000000000000000000000000,
        0xff81fe03fc07f00fe01f803f000000000000000000000000000000000000,
        0xff01fc03f807e00fc01f003e000000000000000000000000000000000000,
        0xfe01f803f007c00f801e003c000000000000000000000000000000000000,
    ];

    // endregion

    // Oracles

    #[generate_trait]
    impl Oracle of OracleTrait {
        /// The tiles of the board by their distance to `position` (`hex_distance`, the per-tile
        /// definition): entry `d` holds the tiles at exactly `d`.
        fn rings(map: HexMap, position: u8) -> Felt252Dict<felt252> {
            let mut rings: Felt252Dict<felt252> = Default::default();
            let size: u8 = map.width * map.height;
            let mut tile: u8 = 0;
            while tile != size {
                let distance: felt252 = map.hex_distance(position, tile).into();
                rings.insert(distance, rings.get(distance) + Bits::pow(tile));
                tile += 1;
            }
            rings
        }

        /// The tiles at most `radius` from the centre of `rings`.
        fn hexagon(ref rings: Felt252Dict<felt252>, radius: u8) -> felt252 {
            // A distance on the board is below `W + H <= 254`
            let last: u16 = if radius > 254 {
                254
            } else {
                radius.into()
            };
            let mut mask: felt252 = 0;
            let mut distance: u16 = 0;
            while distance <= last {
                mask += rings.get(distance.into());
                distance += 1;
            }
            mask
        }

        /// `hexagon` and `hexagon_ring` against the per-tile definition, at the positions
        /// `first..last` of a board, for every radius of `radii`.
        fn check(width: u8, height: u8, first: u8, last: u8, radii: Span<u8>) {
            let map = Self::map(width, height);
            let mut position = first;
            while position != last {
                let mut rings = Self::rings(map, position);
                for radius in radii {
                    let (radius, expected) = (*radius, Self::hexagon(ref rings, *radius));
                    assert!(map.hexagon(position, radius) == expected, "{} {}", position, radius);
                    let ring = rings.get(radius.into());
                    assert!(map.hexagon_ring(position, radius) == ring, "{} {}", position, radius);
                }
                position += 1;
            }
        }

        /// `check` on `count` seeded positions of a board.
        fn seeded(width: u8, height: u8, count: u32, radii: Span<u8>, seed: u64) {
            let size: u16 = width.into() * height.into();
            let mut state = seed;
            let mut index = 0;
            while index != count {
                state = Self::next(state);
                let position = Self::draw(state, 0x100000000, size);
                Self::check(width, height, position, position + 1, radii);
                index += 1;
            }
        }

        /// The table path against the loop path on 15 × 16, positions `first..last`, radius
        /// `1..=7`.
        fn paths(first: u8, last: u8) {
            let mut position = first;
            while position != last {
                let mut radius: u8 = 1;
                while radius != 8 {
                    let table = HexagonInternal::table(HEXAGONS.span(), HEIGHT, position, radius);
                    let rows = HexagonInternal::rows(WIDTH, HEIGHT, position, radius);
                    assert!(table == rows, "{} {}", position, radius);
                    let table = HexagonInternal::table(
                        HEXAGON_RINGS.span(), HEIGHT, position, radius,
                    );
                    let rows = HexagonInternal::ring_rows(WIDTH, HEIGHT, position, radius);
                    assert!(table == rows, "{} {}", position, radius);
                    radius += 1;
                }
                position += 1;
            }
        }

        /// R-N6-5 at the positions `first..last` of 15 × 16, radius `1..=9`.
        fn difference(first: u8, last: u8) {
            let map = Self::map(WIDTH, HEIGHT);
            let mut position = first;
            while position != last {
                let mut inner = map.hexagon(position, 0);
                let mut radius: u8 = 1;
                while radius != 10 {
                    let outer = map.hexagon(position, radius);
                    assert!(map.hexagon_ring(position, radius) == outer - inner);
                    inner = outer;
                    radius += 1;
                }
                position += 1;
            }
        }

        /// The secondary equality with `tiles_within_range` on an empty board, on the centres
        /// whose hexagon is all interior, radius `1..=9`.
        fn flood(width: u8, height: u8, first: u8, last: u8) {
            let map = Self::map(width, height);
            let interior = LayoutTrait::interior(width, height);
            let interior_wide: u256 = interior.into();
            let mut position = first;
            while position != last {
                let mut rings = Self::rings(map, position);
                let mut radius: u8 = 1;
                while radius != 10 {
                    let expected = Self::hexagon(ref rings, radius);
                    if Bits::to_felt(Bits::and(expected.into(), interior_wide)) == expected {
                        let flood = Bfs::tiles_within_range(
                            interior, width, height, position, radius,
                        );
                        assert!(map.hexagon(position, radius) == flood, "{} {}", position, radius);
                    }
                    radius += 1;
                }
                position += 1;
            }
        }

        /// The next state of a 64-bit linear congruential generator (Knuth's MMIX constants).
        fn next(state: u64) -> u64 {
            let product: u128 = state.into() * 6364136223846793005 + 1442695040888963407;
            (product % 0x10000000000000000).try_into().unwrap()
        }

        /// A position of a board of `size` tiles drawn from a state.
        fn draw(state: u64, shift: u64, size: u16) -> u8 {
            let size: u64 = size.into();
            ((state / shift) % size).try_into().unwrap()
        }

        /// A map with no walkable tile (walls are ignored) and no seed.
        fn map(width: u8, height: u8) -> HexMap {
            HexMap { width, height, grid: 0, seed: 0 }
        }

        /// The position of the tile `(x, y)`.
        fn at(width: u8, x: u8, y: u8) -> u8 {
            LayoutTrait::index(width, x, y)
        }
    }

    /// The radii `0..=9`.
    const RADII: [u8; 10] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

    // Regression cases (plan §6.7)

    /// R-N6-1: on 15 × 16, `hexagon((7, 14), 6)` is the per-tile definition, with no bit at
    /// `(1, 0)` or `(2, 0)` (a move before the clip would put some there).
    #[test]
    #[available_gas(l2_gas: 3496944)]
    fn test_hexagon_regression_r_n6_1() {
        let map = Oracle::map(WIDTH, HEIGHT);
        let position = Oracle::at(WIDTH, 7, 14);
        let mut rings = Oracle::rings(map, position);
        let hexagon = map.hexagon(position, 6);
        assert!(hexagon == Oracle::hexagon(ref rings, 6));
        let hexagon: u256 = hexagon.into();
        assert!(!Bits::get(hexagon, Oracle::at(WIDTH, 1, 0)));
        assert!(!Bits::get(hexagon, Oracle::at(WIDTH, 2, 0)));
    }

    /// R-N6-2: on 15 × 16, `hexagon((6, 8), 8)` contains `(14, 8)` (the loop path).
    #[test]
    #[available_gas(l2_gas: 125353)]
    fn test_hexagon_regression_r_n6_2() {
        let map = Oracle::map(WIDTH, HEIGHT);
        let hexagon: u256 = map.hexagon(Oracle::at(WIDTH, 6, 8), 8).into();
        assert!(Bits::get(hexagon, Oracle::at(WIDTH, 14, 8)));
    }

    /// R-N6-3: on 15 × 16, `hexagon((7, 8), 7)` contains `(7, 15)` (the canonical shape reaches
    /// the row 15).
    #[test]
    #[available_gas(l2_gas: 23072)]
    fn test_hexagon_regression_r_n6_3() {
        let map = Oracle::map(WIDTH, HEIGHT);
        let hexagon: u256 = map.hexagon(Oracle::at(WIDTH, 7, 8), 7).into();
        assert!(Bits::get(hexagon, Oracle::at(WIDTH, 7, 15)));
    }

    /// R-N6-4: the sights from `(7, 7)` and `(7, 8)` on 15 × 16 contain no ring tile.
    #[test]
    #[available_gas(l2_gas: 72474)]
    fn test_hexagon_regression_r_n6_4() {
        let map = Oracle::map(WIDTH, HEIGHT);
        let interior: u256 = LayoutTrait::interior(WIDTH, HEIGHT).into();
        for position in [Oracle::at(WIDTH, 7, 7), Oracle::at(WIDTH, 7, 8)].span() {
            let sight = map.hexagon(*position, 6);
            assert!(Bits::to_felt(Bits::and(sight.into(), interior)) == sight);
        }
    }

    /// R-N6-5: `hexagon_ring(p, r) = hexagon(p, r) − hexagon(p, r − 1)` for every position of
    /// 15 × 16 and every radius `1..=9`.
    #[test]
    #[available_gas(l2_gas: 103932871)]
    fn test_hexagon_regression_r_n6_5_0() {
        Oracle::difference(0, 120);
    }

    #[test]
    #[available_gas(l2_gas: 103504922)]
    fn test_hexagon_regression_r_n6_5_1() {
        Oracle::difference(120, 240);
    }

    /// R-N6-6: the radius 0 is `2^p` for both, every position of 15 × 16.
    #[test]
    #[available_gas(l2_gas: 1824239)]
    fn test_hexagon_regression_r_n6_6() {
        let map = Oracle::map(WIDTH, HEIGHT);
        let mut position: u8 = 0;
        while position != 240 {
            assert!(map.hexagon(position, 0) == Bits::pow(position));
            assert!(map.hexagon_ring(position, 0) == Bits::pow(position));
            position += 1;
        }
    }

    /// R-N6-7: on 7 × 7, `hexagon((1, 1), 1)` has 7 tiles, three of them on the ring; the flood
    /// of an empty board has the 4 interior ones, and the two are not equal.
    #[test]
    #[available_gas(l2_gas: 81381)]
    fn test_hexagon_regression_r_n6_7() {
        let map = Oracle::map(7, 7);
        let position = Oracle::at(7, 1, 1);
        let expected = Bits::pow(1)
            + Bits::pow(2)
            + Bits::pow(7)
            + Bits::pow(8)
            + Bits::pow(9)
            + Bits::pow(15)
            + Bits::pow(16);
        assert!(map.hexagon(position, 1) == expected);
        let flood = HexMapTrait::new_empty(7, 7, 0).range(position, 1);
        assert!(flood == Bits::pow(8) + Bits::pow(9) + Bits::pow(15) + Bits::pow(16));
    }

    /// A position outside the board panics.
    #[test]
    #[available_gas(l2_gas: 22901)]
    #[should_panic(expected: ('Asserter: position not inside',))]
    fn test_hexagon_revert_outside() {
        Oracle::map(WIDTH, HEIGHT).hexagon(240, 1);
    }

    #[test]
    #[available_gas(l2_gas: 22901)]
    #[should_panic(expected: ('Asserter: position not inside',))]
    fn test_hexagon_ring_revert_outside() {
        Oracle::map(WIDTH, HEIGHT).hexagon_ring(240, 0);
    }

    // The tables against the per-tile definition at their canonical centres

    #[test]
    #[available_gas(l2_gas: 7792491)]
    fn test_hexagon_tables() {
        let map = Oracle::map(WIDTH, HEIGHT);
        let mut odd: u32 = 0;
        while odd != 2 {
            let centre: u8 = if odd == 0 {
                127
            } else {
                112
            };
            let mut rings = Oracle::rings(map, centre);
            let mut radius: u8 = 1;
            while radius != 8 {
                let key = 7 * odd + radius.into() - 1;
                assert!(*HEXAGONS.span().at(key) == Oracle::hexagon(ref rings, radius));
                assert!(*HEXAGON_RINGS.span().at(key) == rings.get(radius.into()));
                radius += 1;
            }
            odd += 1;
        }
    }

    // The per-tile definition on every position of 15 × 16 and 7 × 7, radius 0..=9

    #[test]
    #[available_gas(l2_gas: 304454000)]
    fn test_hexagon_oracle_15x16_0() {
        Oracle::check(WIDTH, HEIGHT, 0, 60, RADII.span());
    }

    #[test]
    #[available_gas(l2_gas: 307232999)]
    fn test_hexagon_oracle_15x16_1() {
        Oracle::check(WIDTH, HEIGHT, 60, 120, RADII.span());
    }

    #[test]
    #[available_gas(l2_gas: 307250261)]
    fn test_hexagon_oracle_15x16_2() {
        Oracle::check(WIDTH, HEIGHT, 120, 180, RADII.span());
    }

    #[test]
    #[available_gas(l2_gas: 305047764)]
    fn test_hexagon_oracle_15x16_3() {
        Oracle::check(WIDTH, HEIGHT, 180, 240, RADII.span());
    }

    #[test]
    #[available_gas(l2_gas: 115055409)]
    fn test_hexagon_oracle_7x7() {
        Oracle::check(7, 7, 0, 49, RADII.span());
    }

    // The per-tile definition on every position of 3 × 83, radius 41 and 255

    #[test]
    #[available_gas(l2_gas: 667888788)]
    fn test_hexagon_oracle_3x83_0() {
        Oracle::check(3, 83, 0, 83, [41, 255].span());
    }

    #[test]
    #[available_gas(l2_gas: 691166060)]
    fn test_hexagon_oracle_3x83_1() {
        Oracle::check(3, 83, 83, 166, [41, 255].span());
    }

    #[test]
    #[available_gas(l2_gas: 669585903)]
    fn test_hexagon_oracle_3x83_2() {
        Oracle::check(3, 83, 166, 249, [41, 255].span());
    }

    // The per-tile definition on 32 seeded positions of every other dimension class of the engine,
    // radius 0..=9, both sides of `LOOP_RADIUS` (100, 101) and 255 (the whole board); the boards
    // of 83 and 25 columns also at a mid radius, 20

    /// The radii of the seeded cases.
    const SEEDED_RADII: [u8; 13] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 100, 101, 255];
    /// The same and a mid radius, for the widest boards.
    const SEEDED_RADII_WIDE: [u8; 14] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 20, 100, 101, 255];

    #[test]
    #[available_gas(l2_gas: 268645902)]
    fn test_hexagon_oracle_seeded_15x15() {
        Oracle::seeded(15, 15, 32, SEEDED_RADII.span(), 'h15x15');
    }

    #[test]
    #[available_gas(l2_gas: 301139601)]
    fn test_hexagon_oracle_seeded_16x15() {
        Oracle::seeded(16, 15, 32, SEEDED_RADII.span(), 'h16x15');
    }

    #[test]
    #[available_gas(l2_gas: 297540726)]
    fn test_hexagon_oracle_seeded_17x14() {
        Oracle::seeded(17, 14, 32, SEEDED_RADII.span(), 'h17x14');
    }

    #[test]
    #[available_gas(l2_gas: 298277669)]
    fn test_hexagon_oracle_seeded_19x13() {
        Oracle::seeded(19, 13, 32, SEEDED_RADII.span(), 'h19x13');
    }

    #[test]
    #[available_gas(l2_gas: 303094596)]
    fn test_hexagon_oracle_seeded_25x10() {
        Oracle::seeded(25, 10, 32, SEEDED_RADII_WIDE.span(), 'h25x10');
    }

    #[test]
    #[available_gas(l2_gas: 273610974)]
    fn test_hexagon_oracle_seeded_83x3() {
        Oracle::seeded(83, 3, 32, SEEDED_RADII_WIDE.span(), 'h83x3');
    }

    #[test]
    #[available_gas(l2_gas: 137777367)]
    fn test_hexagon_oracle_seeded_3x3() {
        Oracle::seeded(3, 3, 32, SEEDED_RADII.span(), 'h3x3');
    }

    /// The width 15 below 16 rows (the clip of the rows at the top on the table path).
    #[test]
    #[available_gas(l2_gas: 615210158)]
    fn test_hexagon_oracle_seeded_15xh() {
        let mut height: u8 = 3;
        while height != 15 {
            Oracle::seeded(15, height, 8, SEEDED_RADII.span(), height.into());
            height += 1;
        }
    }

    // The table path against the loop path, every position of 15 × 16, radius 1..=7

    #[test]
    #[available_gas(l2_gas: 165278890)]
    fn test_hexagon_paths_0() {
        Oracle::paths(0, 120);
    }

    #[test]
    #[available_gas(l2_gas: 165011465)]
    fn test_hexagon_paths_1() {
        Oracle::paths(120, 240);
    }

    // The secondary equality with `tiles_within_range`, on the centres whose hexagon is all
    // interior

    #[test]
    #[available_gas(l2_gas: 528014472)]
    fn test_hexagon_flood_15x16_0() {
        Oracle::flood(WIDTH, HEIGHT, 0, 120);
    }

    #[test]
    #[available_gas(l2_gas: 529966485)]
    fn test_hexagon_flood_15x16_1() {
        Oracle::flood(WIDTH, HEIGHT, 120, 240);
    }

    #[test]
    #[available_gas(l2_gas: 56570004)]
    fn test_hexagon_flood_7x7() {
        Oracle::flood(7, 7, 0, 49);
    }

    /// The per-position variant equals `hexagon` at the radius 6 on every position of 15 × 16.
    #[test]
    #[available_gas(l2_gas: 8241910)]
    fn test_hexagon_variant() {
        let map = Oracle::map(WIDTH, HEIGHT);
        let mut position: u8 = 0;
        while position != 240 {
            assert!(*SIGHTS.span().at(position.into()) == map.hexagon(position, 6));
            position += 1;
        }
    }

    // Benchmarks, on the worst cases of plan §6.7: the difference between a test that calls twice
    // and one that calls once, the method of `bench_assembly`; the second call is the measured
    // case.

    #[derive(Copy, Drop)]
    struct Bench {
        /// The sight, table path: radius 6 from `(7, 7)`, then from `(7, 8)` (the tick's figure).
        sight: [(u8, u8); 2],
        /// The table path, maximal clipping: radius 7 from `(13, 1)`, then from `(1, 1)`.
        clip: [(u8, u8); 2],
        /// The loop path on 15 × 16 (16 rows): radius 9, then 8, from `(7, 8)`.
        board: [(u8, u8); 2],
        /// The loop path on 15 × 16 (16 rows): radius 8, then 9, from `(7, 8)`.
        board_wide: [(u8, u8); 2],
        /// The loop path on 3 × 83 (83 rows): radius 255 from `(1, 40)`, then from `(1, 41)`.
        tall: [(u8, u8); 2],
        /// The ring on 3 × 83 (83 rows): radius 41 from `(1, 40)`, then from `(1, 41)` (its first
        /// and last rows are the rows 0 and 82, whole; at the radius 255 the ring is empty).
        tall_ring: [(u8, u8); 2],
    }

    #[generate_trait]
    impl Inputs of InputsTrait {
        /// The inputs, opaque to the compiler (`#[inline(never)]`, as in `bench_assembly`).
        #[inline(never)]
        fn get() -> Bench {
            Bench {
                sight: [(112, 6), (127, 6)],
                clip: [(28, 7), (16, 7)],
                board: [(127, 9), (127, 8)],
                board_wide: [(127, 8), (127, 9)],
                tall: [(121, 255), (124, 255)],
                tall_ring: [(121, 41), (124, 41)],
            }
        }
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 35973)]
    fn bench_hexagon_sight_once() {
        let [(position, radius), _] = Inputs::get().sight;
        assert!(Oracle::map(WIDTH, HEIGHT).hexagon(position, radius) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 53225)]
    fn bench_hexagon_sight_twice() {
        let [(position, radius), (other, next)] = Inputs::get().sight;
        let map = Oracle::map(WIDTH, HEIGHT);
        assert!(map.hexagon(position, radius) != 0);
        assert!(map.hexagon(other, next) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 35973)]
    fn bench_hexagon_ring_sight_once() {
        let [(position, radius), _] = Inputs::get().sight;
        assert!(Oracle::map(WIDTH, HEIGHT).hexagon_ring(position, radius) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 53225)]
    fn bench_hexagon_ring_sight_twice() {
        let [(position, radius), (other, next)] = Inputs::get().sight;
        let map = Oracle::map(WIDTH, HEIGHT);
        assert!(map.hexagon_ring(position, radius) != 0);
        assert!(map.hexagon_ring(other, next) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 50984)]
    fn bench_hexagon_clip_once() {
        let [(position, radius), _] = Inputs::get().clip;
        assert!(Oracle::map(WIDTH, HEIGHT).hexagon(position, radius) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 82417)]
    fn bench_hexagon_clip_twice() {
        let [(position, radius), (other, next)] = Inputs::get().clip;
        let map = Oracle::map(WIDTH, HEIGHT);
        assert!(map.hexagon(position, radius) != 0);
        assert!(map.hexagon(other, next) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 50984)]
    fn bench_hexagon_ring_clip_once() {
        let [(position, radius), _] = Inputs::get().clip;
        assert!(Oracle::map(WIDTH, HEIGHT).hexagon_ring(position, radius) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 82417)]
    fn bench_hexagon_ring_clip_twice() {
        let [(position, radius), (other, next)] = Inputs::get().clip;
        let map = Oracle::map(WIDTH, HEIGHT);
        assert!(map.hexagon_ring(position, radius) != 0);
        assert!(map.hexagon_ring(other, next) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 152985)]
    fn bench_hexagon_loop_board_once() {
        let [(position, radius), _] = Inputs::get().board;
        assert!(Oracle::map(WIDTH, HEIGHT).hexagon(position, radius) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 288089)]
    fn bench_hexagon_loop_board_twice() {
        let [(position, radius), (other, next)] = Inputs::get().board;
        let map = Oracle::map(WIDTH, HEIGHT);
        assert!(map.hexagon(position, radius) != 0);
        assert!(map.hexagon(other, next) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 158529)]
    fn bench_hexagon_ring_loop_board_once() {
        let [(position, radius), _] = Inputs::get().board;
        assert!(Oracle::map(WIDTH, HEIGHT).hexagon_ring(position, radius) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 299460)]
    fn bench_hexagon_ring_loop_board_twice() {
        let [(position, radius), (other, next)] = Inputs::get().board;
        let map = Oracle::map(WIDTH, HEIGHT);
        assert!(map.hexagon_ring(position, radius) != 0);
        assert!(map.hexagon_ring(other, next) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 153825)]
    fn bench_hexagon_loop_board_wide_once() {
        let [(position, radius), _] = Inputs::get().board_wide;
        assert!(Oracle::map(WIDTH, HEIGHT).hexagon(position, radius) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 288089)]
    fn bench_hexagon_loop_board_wide_twice() {
        let [(position, radius), (other, next)] = Inputs::get().board_wide;
        let map = Oracle::map(WIDTH, HEIGHT);
        assert!(map.hexagon(position, radius) != 0);
        assert!(map.hexagon(other, next) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 159653)]
    fn bench_hexagon_ring_loop_board_wide_once() {
        let [(position, radius), _] = Inputs::get().board_wide;
        assert!(Oracle::map(WIDTH, HEIGHT).hexagon_ring(position, radius) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 299460)]
    fn bench_hexagon_ring_loop_board_wide_twice() {
        let [(position, radius), (other, next)] = Inputs::get().board_wide;
        let map = Oracle::map(WIDTH, HEIGHT);
        assert!(map.hexagon_ring(position, radius) != 0);
        assert!(map.hexagon_ring(other, next) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 564060)]
    fn bench_hexagon_loop_tall_once() {
        let [(position, radius), _] = Inputs::get().tall;
        assert!(Oracle::map(3, 83).hexagon(position, radius) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 1109892)]
    fn bench_hexagon_loop_tall_twice() {
        let [(position, radius), (other, next)] = Inputs::get().tall;
        let map = Oracle::map(3, 83);
        assert!(map.hexagon(position, radius) != 0);
        assert!(map.hexagon(other, next) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 586446)]
    fn bench_hexagon_ring_loop_tall_once() {
        let [(position, radius), _] = Inputs::get().tall_ring;
        assert!(Oracle::map(3, 83).hexagon_ring(position, radius) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 1161500)]
    fn bench_hexagon_ring_loop_tall_twice() {
        let [(position, radius), (other, next)] = Inputs::get().tall_ring;
        let map = Oracle::map(3, 83);
        assert!(map.hexagon_ring(position, radius) != 0);
        assert!(map.hexagon_ring(other, next) != 0);
    }

    #[generate_trait]
    impl Variant of VariantTrait {
        /// The per-position variant (plan §6.7, "Why not the flood"), not shipped: one lookup of
        /// `SIGHTS` after the same check of the position as `hexagon`.
        #[inline(always)]
        fn sight(map: HexMap, position: u8) -> felt252 {
            Asserter::assert_inside(map.width, map.height, position);
            *SIGHTS.span().at(position.into())
        }
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 21189)]
    fn bench_hexagon_variant_once() {
        let [(position, _), _] = Inputs::get().sight;
        assert!(Variant::sight(Oracle::map(WIDTH, HEIGHT), position) != 0);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 23541)]
    fn bench_hexagon_variant_twice() {
        let [(position, _), (other, _)] = Inputs::get().sight;
        let map = Oracle::map(WIDTH, HEIGHT);
        assert!(Variant::sight(map, position) != 0);
        assert!(Variant::sight(map, other) != 0);
    }
}
