//! N-5, line of sight (plan §6.6): the tiles strictly between two tiles of a board, whether walls
//! block the sight between them, and from which side a target is approached.
//!
//! The line is the mirror's integer line (`HexTrait::line_to`) between the `Hex` of both tiles
//! (plan §3.5), with the game's tie rule: the lower tile index, that is the smaller row, and on
//! the same row the smaller column. It is symmetric and translation-invariant. A line one of whose
//! tiles leaves the board is `None`, never clipped (D-27): at a tie on the same row the preferred
//! tile may lie at column `−1` (R-N5-1).
//!
//! Two paths give the same result. The **table path** serves the width 15 and a distance of at
//! most 6 (the game's sight): one division, one entry of `LINES` and one product. The **loop path**
//! serves every other pair: the accumulators of `line_to`, walked on the board one direction at a
//! time, at most `W + H − 2` steps (plan §6.6, "Dispatch").
//!
//! Mirrors nothing in `hexx`: an extension (plan §6.6, N-5).

// Core imports

#[feature("bounded-int-utils")]
use core::internal::bounded_int::{
    BoundedInt, ConstrainHelper, MulHelper, SubHelper, constrain, mul, sub,
};

// Internal imports

use hexx::board::asserter::errors;
use hexx::board::bits::Bits;
use hexx::board::direction::Direction;
use hexx::board::layout::LayoutTrait;
use hexx::board::map::HexMap;

// Constants

/// 1/2 in the field.
const INV_2: felt252 = 0x400000000000008800000000000000000000000000000000000000000000001;
/// 2, as a divisor.
const TWO: NonZero<u8> = 2;
/// 30, as a divisor: on the width 15, `position mod 30` is the column, plus 15 on an odd row.
const THIRTY: NonZero<u8> = 30;
/// The width the table path serves.
const TABLE_WIDTH: u8 = 15;

/// `W * H` for any `u8` dimensions.
impl SizeMul of MulHelper<u8, u8> {
    type Result = BoundedInt<0, 65025>;
}

/// `position - W * H`.
impl PositionSub of SubHelper<u8, BoundedInt<0, 65025>> {
    type Result = BoundedInt<-65025, 255>;
}

/// Sign of `position - W * H`.
impl PositionConstrain of ConstrainHelper<BoundedInt<-65025, 255>, 0> {
    type LowT = BoundedInt<-65025, -1>;
    type HighT = BoundedInt<0, 255>;
}

// region generated by `cargo run --manifest-path tools/refgen/Cargo.toml -- gen line`: do not edit

/// The smallest `to − from` of the table, its key offset.
const OFFSET: felt252 = 93;
/// The keys of one parity: `to − from + OFFSET` is below it.
const SPAN: felt252 = 187;
/// The entries of the table path, by key `to − from + OFFSET + SPAN · (row of from is odd)`,
/// on the width 15: `(mask · 2^-c, lo, hi, lo_to, hi_to)`, where `mask` is the between-mask of the
/// line from the canonical start `c` (`(7, 8)`, index 127, for an even row; `(7, 7)`, index 112,
/// for an odd one) to `c + to − from`, `lo..=hi` the values of `from mod 30` for which every
/// tile of the line lies in the columns `0..15`, and `lo_to..=hi_to` those for which the target
/// does (`from mod 30` is the column plus 15 on an odd row). A key beyond the radius 6 has the
/// empty ranges `(0, 30, 0, 30, 0)`.
const LINES: [(felt252, u8, u8, u8, u8); 374] = [
    (0x7fff7ffeffff010dfeedfddffddffbbffbc0000000000000000000000000001, 3, 14, 3, 14),
    (0x7fff7ffeffff010bfeebfddffddff77ff780000000000000000000000000001, 2, 14, 2, 14),
    (0x7fff7ffdfffe010bfee7fbbffbbff77fef00000000000000000000000000001, 1, 14, 1, 14),
    (0x7fff7ffdfffe0107fee7fbbffbbfeeffef00000000000000000000000000001, 1, 14, 0, 14),
    (0x7ffefffdfffc00fffdcffbbff77fddffde00000000000000000000000000001, 0, 13, 0, 13),
    (0x7ffefffbfffc00fffdbff77ff77fddffbc00000000000000000000000000001, 0, 12, 0, 12),
    (0x7ffefffbfff800effd9ff77feeffbbff7800000000000000000000000000001, 0, 11, 0, 11),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x7fff7ffefffe810efeeffddffccffde00000000000000000000000000000001, 4, 14, 4, 14),
    (0x7fff7ffeffff010dfeeffddffddffbc00000000000000000000000000000001, 3, 14, 3, 14),
    (0x7fff7ffefffe010bfeeffddffbbff7800000000000000000000000000000001, 2, 14, 2, 14),
    (0x7fff7ffdfffe0107feeffbbffbbfef000000000000000000000000000000001, 1, 14, 1, 14),
    (0x7ffefffdfffc0107fddffbbff77fef000000000000000000000000000000001, 0, 14, 0, 14),
    (0x7ffefffbfffc00fffddff77ff77fde000000000000000000000000000000001, 0, 13, 0, 13),
    (0x7ffefffbfff800effddff77feeffbc000000000000000000000000000000001, 0, 12, 0, 12),
    (0x7ffefffbffe800cffddff77fccff78000000000000000000000000000000001, 0, 11, 0, 11),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x7fff3fff7fff410ffe67feeffe6800000000000000000000000000000000001, 4, 14, 4, 14),
    (0x7fff7ffe7fff810ffeeffccffef000000000000000000000000000000000001, 3, 14, 3, 14),
    (0x7fff7ffeffff010ffeeffddffde000000000000000000000000000000000001, 2, 14, 2, 14),
    (0x7fff7ffefffe010ffeeffddffbc000000000000000000000000000000000001, 1, 14, 1, 14),
    (0x7fff7ffdfffe010ffeeffbbffbc000000000000000000000000000000000001, 1, 14, 0, 14),
    (0x7ffefffdfffc010ffddffbbff78000000000000000000000000000000000001, 0, 13, 0, 13),
    (0x7ffefffbfff8010ffddff77fef0000000000000000000000000000000000001, 0, 12, 0, 12),
    (0x7ffefff3fff0010ffddfe67fde0000000000000000000000000000000000001, 0, 11, 0, 11),
    (0x7ffcfff7ffd0010ff99feeff9a0000000000000000000000000000000000001, 0, 10, 0, 10),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0),
    (0x7fff3fff3fffc10ffe67fe67ff7800000000000000000000000000000000001, 5, 14, 5, 14),
    (0x7fff3fff4000010ffe67fe68000000000000000000000000000000000000001, 4, 14, 4, 14),
    (0x7fff7ffe8000010ffeeffcd0000000000000000000000000000000000000001, 3, 14, 3, 14),
    (0x7fff7fff0000010ffeeffde0000000000000000000000000000000000000001, 2, 14, 2, 14),
    (0x7fff7ffe0000010ffeeffbc0000000000000000000000000000000000000001, 1, 14, 1, 14),
    (0x7ffefffe0000010ffddffbc0000000000000000000000000000000000000001, 0, 14, 0, 14),
    (0x7ffefffc0000010ffddff780000000000000000000000000000000000000001, 0, 13, 0, 13),
    (0x7ffefff40000010ffddfe680000000000000000000000000000000000000001, 0, 12, 0, 12),
    (0x7ffcffe80000010ff99fcd00000000000000000000000000000000000000001, 0, 11, 0, 11),
    (0x7ffcffe7ffe0010ff99fccffbc0000000000000000000000000000000000001, 0, 10, 0, 10),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0),
    (0x3fff8fffe0000087ff11ffbc000000000000000000000000000000000000001, 5, 14, 5, 14),
    (0x3fff9fffc0000087ff33ff78000000000000000000000000000000000000001, 4, 14, 4, 14),
    (0x7fff3fff8000010ffe67fef0000000000000000000000000000000000000001, 3, 14, 3, 14),
    (0x7fff40000000010ffe680000000000000000000000000000000000000000001, 2, 14, 2, 14),
    (0x7fff80000000010ffef00000000000000000000000000000000000000000001, 1, 14, 1, 14),
    (0x7fff80000000010ffef00000000000000000000000000000000000000000001, 1, 14, 0, 14),
    (0x7fff00000000010ffde00000000000000000000000000000000000000000001, 0, 13, 0, 13),
    (0x7ffd00000000010ff9a00000000000000000000000000000000000000000001, 0, 12, 0, 12),
    (0x7ffcfff80000010ff99fef00000000000000000000000000000000000000001, 0, 11, 0, 11),
    (0x7ff9fff00000010ff33fde00000000000000000000000000000000000000003, 0, 10, 0, 10),
    (0x7ff1ffe00000010fe23fbc00000000000000000000000000000000000000003, 0, 9, 0, 9),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x1fffc80000000043ff890000000000000000000000000000000000000000001, 6, 14, 6, 14),
    (0x1fffd00000000043ff9a0000000000000000000000000000000000000000001, 5, 14, 5, 14),
    (0x3fffa00000000087ff340000000000000000000000000000000000000000001, 4, 14, 4, 14),
    (0x3fffc00000000087ff780000000000000000000000000000000000000000001, 3, 14, 3, 14),
    (0x7fff80000000010ffef00000000000000000000000000000000000000000001, 2, 14, 2, 14),
    (0x0, 1, 14, 1, 14), (0x0, 0, 14, 0, 14),
    (0x7fff00000000010ffde00000000000000000000000000000000000000000001, 0, 13, 0, 13),
    (0x7ffe00000000010ffbc00000000000000000000000000000000000000000003, 0, 12, 0, 12),
    (0x7ffa00000000010ff3400000000000000000000000000000000000000000003, 0, 11, 0, 11),
    (0x7ff400000000010fe6800000000000000000000000000000000000000000007, 0, 10, 0, 10),
    (0x7fe400000000010fc4800000000000000000000000000000000000000000007, 0, 9, 0, 9),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x40000000000000880000000000000000000000000000000000000000000001, 6, 14, 6, 14),
    (0x80000000000001100000000000000000000000000000000000000000000001, 5, 14, 5, 14),
    (0x100000000000002200000000000000000000000000000000000000000000001, 4, 14, 4, 14),
    (0x200000000000004400000000000000000000000000000000000000000000001, 3, 14, 3, 14),
    (0x400000000000008800000000000000000000000000000000000000000000001, 2, 14, 2, 14),
    (0x0, 1, 14, 1, 14), (0x0, 0, 14, 0, 14), (0x0, 0, 13, 0, 13), (0x2, 0, 12, 0, 12),
    (0x6, 0, 11, 0, 11), (0xe, 0, 10, 0, 10), (0x1e, 0, 9, 0, 9), (0x3e, 0, 8, 0, 8),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x100000000000002200000000000000000000000000000000000000000000c01, 6, 14, 6, 14),
    (0x200000000000004400000000000000000000000000000000000000000001801, 5, 14, 5, 14),
    (0x200000000000004400000000000000000000000000000000000000000001001, 4, 14, 4, 14),
    (0x400000000000008800000000000000000000000000000000000000000002001, 3, 14, 3, 14),
    (0x400000000000008800000000000000000000000000000000000000000000001, 2, 14, 2, 14),
    (0x0, 1, 14, 1, 14), (0x0, 0, 14, 0, 14), (0x2, 0, 13, 0, 13), (0x10002, 0, 12, 0, 12),
    (0x20006, 0, 11, 0, 11), (0x60006, 0, 10, 0, 10), (0xc000e, 0, 9, 0, 9), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x400000000000008800000000000000000000000000000000000000004003801, 5, 14, 5, 14),
    (0x400000000000008800000000000000000000000000000000000000008003001, 4, 14, 4, 14),
    (0x400000000000008800000000000000000000000000000000000000000003001, 3, 14, 3, 14),
    (0x6000, 2, 14, 2, 14), (0x4000, 1, 14, 1, 14), (0x4000, 1, 14, 0, 14), (0x8000, 0, 13, 0, 13),
    (0x18000, 0, 12, 0, 12), (0x30002, 0, 11, 0, 11), (0x200030002, 0, 10, 0, 10),
    (0x400070002, 0, 9, 0, 9), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0),
    (0x40000000000000880000000000000000000000000000000000000000c003001, 5, 14, 5, 14),
    (0x18006000, 4, 14, 4, 14), (0x10006000, 3, 14, 3, 14), (0x20004000, 2, 14, 2, 14),
    (0x40004000, 1, 14, 1, 14), (0x40008000, 0, 14, 0, 14), (0x80008000, 0, 13, 0, 13),
    (0x100018000, 0, 12, 0, 12), (0x300018000, 0, 11, 0, 11), (0x600030002, 0, 10, 0, 10),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x60010006000, 4, 14, 4, 14),
    (0x40030004000, 3, 14, 3, 14), (0x80020004000, 2, 14, 2, 14), (0x100020004000, 1, 14, 1, 14),
    (0x100040004000, 1, 14, 0, 14), (0x200040008000, 0, 13, 0, 13), (0x400080008000, 0, 12, 0, 12),
    (0x800180008000, 0, 11, 0, 11), (0x1800100018000, 0, 10, 0, 10), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0), (0x200040030004000, 4, 14, 4, 14), (0x400080020004000, 3, 14, 3, 14),
    (0x800100020004000, 2, 14, 2, 14), (0x1000100040004000, 1, 14, 1, 14),
    (0x1000200040008000, 0, 14, 0, 14), (0x2000200080008000, 0, 13, 0, 13),
    (0x4000400080008000, 0, 12, 0, 12), (0x8000800180008000, 0, 11, 0, 11), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x1000400080020004000, 3, 14, 3, 14), (0x2000800080020004000, 2, 14, 2, 14),
    (0x4000800100040004000, 1, 14, 1, 14), (0x4001000100040004000, 1, 14, 0, 14),
    (0x8002000200040008000, 0, 13, 0, 13), (0x10002000200080008000, 0, 12, 0, 12),
    (0x20004000400080008000, 0, 11, 0, 11),
    (0x7ffefffefffe010dfddbfddffbbffbbff780000000000000000000000000001, 18, 29, 18, 29),
    (0x7ffefffefffe010bfdd7fddffbbff77fef00000000000000000000000000001, 17, 29, 17, 29),
    (0x7ffefffdfffc010bfdcffbbff77ff77fde00000000000000000000000000001, 16, 29, 16, 29),
    (0x7ffefffdfffc0107fdcffbbff77feeffde00000000000000000000000000001, 15, 29, 15, 29),
    (0x7ffdfffdfff800fffb9ffbbfeeffddffbc00000000000000000000000000001, 15, 28, 15, 28),
    (0x7ffdfffbfff800fffb7ff77feeffddff7800000000000000000000000000001, 15, 27, 15, 27),
    (0x7ffdfffbfff000effb3ff77fddffbbfef000000000000000000000000000001, 15, 26, 15, 26),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x7ffefffefffd010efddffddff99ffde00000000000000000000000000000001, 18, 29, 18, 29),
    (0x7ffefffefffe010dfddffddffbbffbc00000000000000000000000000000001, 17, 29, 17, 29),
    (0x7ffefffefffc010bfddffddff77ff7800000000000000000000000000000001, 16, 29, 16, 29),
    (0x7ffefffdfffc0107fddffbbff77fef000000000000000000000000000000001, 15, 29, 15, 29),
    (0x7ffdfffdfff80107fbbffbbfeeffef000000000000000000000000000000001, 15, 28, 15, 28),
    (0x7ffdfffbfff800fffbbff77feeffde000000000000000000000000000000001, 15, 27, 15, 27),
    (0x7ffdfffbfff000effbbff77fddffbc000000000000000000000000000000001, 15, 26, 15, 26),
    (0x7ffdfffbffd000cffbbff77f99ff78000000000000000000000000000000001, 15, 25, 15, 25),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x7ffe7fff7ffe810ffccffeeffcd000000000000000000000000000000000001, 19, 29, 19, 29),
    (0x7ffefffe7fff010ffddffccffde000000000000000000000000000000000001, 18, 29, 18, 29),
    (0x7ffefffefffe010ffddffddffbc000000000000000000000000000000000001, 17, 29, 17, 29),
    (0x7ffefffefffc010ffddffddff78000000000000000000000000000000000001, 16, 29, 16, 29),
    (0x7ffefffdfffc010ffddffbbff78000000000000000000000000000000000001, 15, 29, 15, 29),
    (0x7ffdfffdfff8010ffbbffbbfef0000000000000000000000000000000000001, 15, 28, 15, 28),
    (0x7ffdfffbfff0010ffbbff77fde0000000000000000000000000000000000001, 15, 27, 15, 27),
    (0x7ffdfff3ffe0010ffbbfe67fbc0000000000000000000000000000000000001, 15, 26, 15, 26),
    (0x7ff9fff7ffa0010ff33feeff340000000000000000000000000000000000001, 15, 25, 15, 25),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x7ffe7fff3fff810ffccffe67fef000000000000000000000000000000000001, 19, 29, 19, 29),
    (0x7ffe7fff4000010ffccffe68000000000000000000000000000000000000001, 18, 29, 18, 29),
    (0x7ffefffe8000010ffddffcd0000000000000000000000000000000000000001, 17, 29, 17, 29),
    (0x7ffeffff0000010ffddffde0000000000000000000000000000000000000001, 16, 29, 16, 29),
    (0x7ffefffe0000010ffddffbc0000000000000000000000000000000000000001, 15, 29, 15, 29),
    (0x7ffdfffe0000010ffbbffbc0000000000000000000000000000000000000001, 15, 28, 15, 28),
    (0x7ffdfffc0000010ffbbff780000000000000000000000000000000000000001, 15, 27, 15, 27),
    (0x7ffdfff40000010ffbbfe680000000000000000000000000000000000000001, 15, 26, 15, 26),
    (0x7ff9ffe80000010ff33fcd00000000000000000000000000000000000000001, 15, 25, 15, 25),
    (0x7ff9ffe7ffc0010ff33fccff780000000000000000000000000000000000001, 15, 24, 15, 24),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x3fff1fffe0000087fe23ffbc000000000000000000000000000000000000001, 20, 29, 20, 29),
    (0x3fff3fffc0000087fe67ff78000000000000000000000000000000000000001, 19, 29, 19, 29),
    (0x7ffe7fff8000010ffccffef0000000000000000000000000000000000000001, 18, 29, 18, 29),
    (0x7ffe80000000010ffcd00000000000000000000000000000000000000000001, 17, 29, 17, 29),
    (0x7fff00000000010ffde00000000000000000000000000000000000000000001, 16, 29, 16, 29),
    (0x7fff00000000010ffde00000000000000000000000000000000000000000001, 15, 29, 15, 29),
    (0x7ffe00000000010ffbc00000000000000000000000000000000000000000001, 15, 28, 15, 28),
    (0x7ffa00000000010ff3400000000000000000000000000000000000000000001, 15, 27, 15, 27),
    (0x7ff9fff80000010ff33fef00000000000000000000000000000000000000001, 15, 26, 15, 26),
    (0x7ff3fff00000010fe67fde00000000000000000000000000000000000000003, 15, 25, 15, 25),
    (0x7fe3ffe00000010fc47fbc00000000000000000000000000000000000000003, 15, 24, 15, 24),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x1fff900000000043ff120000000000000000000000000000000000000000001, 20, 29, 20, 29),
    (0x1fffa00000000043ff340000000000000000000000000000000000000000001, 19, 29, 19, 29),
    (0x3fff400000000087fe680000000000000000000000000000000000000000001, 18, 29, 18, 29),
    (0x3fff800000000087fef00000000000000000000000000000000000000000001, 17, 29, 17, 29),
    (0x7fff00000000010ffde00000000000000000000000000000000000000000001, 16, 29, 16, 29),
    (0x0, 15, 29, 15, 29), (0x0, 15, 28, 15, 28),
    (0x7ffe00000000010ffbc00000000000000000000000000000000000000000001, 15, 27, 15, 27),
    (0x7ffc00000000010ff7800000000000000000000000000000000000000000003, 15, 26, 15, 26),
    (0x7ff400000000010fe6800000000000000000000000000000000000000000003, 15, 25, 15, 25),
    (0x7fe800000000010fcd000000000000000000000000000000000000000000007, 15, 24, 15, 24),
    (0x7fc800000000010f89000000000000000000000000000000000000000000007, 15, 23, 15, 23),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x40000000000000880000000000000000000000000000000000000000000001, 21, 29, 21, 29),
    (0x80000000000001100000000000000000000000000000000000000000000001, 20, 29, 20, 29),
    (0x100000000000002200000000000000000000000000000000000000000000001, 19, 29, 19, 29),
    (0x200000000000004400000000000000000000000000000000000000000000001, 18, 29, 18, 29),
    (0x400000000000008800000000000000000000000000000000000000000000001, 17, 29, 17, 29),
    (0x0, 16, 29, 16, 29), (0x0, 15, 29, 15, 29), (0x0, 15, 28, 15, 28), (0x2, 15, 27, 15, 27),
    (0x6, 15, 26, 15, 26), (0xe, 15, 25, 15, 25), (0x1e, 15, 24, 15, 24), (0x3e, 15, 23, 15, 23),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x100000000000002200000000000000000000000000000000000000000001801, 20, 29, 20, 29),
    (0x200000000000004400000000000000000000000000000000000000000003001, 19, 29, 19, 29),
    (0x200000000000004400000000000000000000000000000000000000000002001, 18, 29, 18, 29),
    (0x400000000000008800000000000000000000000000000000000000000004001, 17, 29, 17, 29),
    (0x400000000000008800000000000000000000000000000000000000000000001, 16, 29, 16, 29),
    (0x0, 15, 29, 15, 29), (0x0, 15, 28, 15, 28), (0x2, 15, 27, 15, 27), (0x20002, 15, 26, 15, 26),
    (0x40006, 15, 25, 15, 25), (0xc0006, 15, 24, 15, 24), (0x18000e, 15, 23, 15, 23),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x400000000000008800000000000000000000000000000000000000004007001, 20, 29, 20, 29),
    (0x400000000000008800000000000000000000000000000000000000008006001, 19, 29, 19, 29),
    (0x400000000000008800000000000000000000000000000000000000000006001, 18, 29, 18, 29),
    (0xc000, 17, 29, 17, 29), (0x8000, 16, 29, 16, 29), (0x8000, 15, 29, 15, 29),
    (0x10000, 15, 28, 15, 28), (0x30000, 15, 27, 15, 27), (0x60002, 15, 26, 15, 26),
    (0x200060002, 15, 25, 15, 25), (0x4000e0002, 15, 24, 15, 24), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x40000000000000880000000000000000000000000000000000000000c006001, 19, 29, 19, 29),
    (0x1800c000, 18, 29, 18, 29), (0x1000c000, 17, 29, 17, 29), (0x20008000, 16, 29, 16, 29),
    (0x40008000, 15, 29, 15, 29), (0x40010000, 15, 28, 15, 28), (0x80010000, 15, 27, 15, 27),
    (0x100030000, 15, 26, 15, 26), (0x300030000, 15, 25, 15, 25), (0x600060002, 15, 24, 15, 24),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0), (0xc001000c000, 19, 29, 19, 29), (0x80030008000, 18, 29, 18, 29),
    (0x100020008000, 17, 29, 17, 29), (0x200020008000, 16, 29, 16, 29),
    (0x200040008000, 15, 29, 15, 29), (0x400040010000, 15, 28, 15, 28),
    (0x800080010000, 15, 27, 15, 27), (0x1000180010000, 15, 26, 15, 26),
    (0x3000100030000, 15, 25, 15, 25), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0), (0x200080030008000, 18, 29, 18, 29), (0x400100020008000, 17, 29, 17, 29),
    (0x800200020008000, 16, 29, 16, 29), (0x1000200040008000, 15, 29, 15, 29),
    (0x1000400040010000, 15, 28, 15, 28), (0x2000400080010000, 15, 27, 15, 27),
    (0x4000800080010000, 15, 26, 15, 26), (0x8001000180010000, 15, 25, 15, 25), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0),
    (0x0, 30, 0, 30, 0), (0x0, 30, 0, 30, 0), (0x2000400100020008000, 18, 29, 18, 29),
    (0x4000800100020008000, 17, 29, 17, 29), (0x8000800200040008000, 16, 29, 16, 29),
    (0x8001000200040008000, 15, 29, 15, 29), (0x10002000400040010000, 15, 28, 15, 28),
    (0x20002000400080010000, 15, 27, 15, 27), (0x40004000800080010000, 15, 26, 15, 26),
];

// endregion

/// One step of the loop path on the board: the position as a bit, its column and the parity of
/// its row.
#[derive(Copy, Drop)]
struct Cursor {
    bit: felt252,
    column: u8,
    odd: bool,
}

/// The constants of the loop path: the last column and the six shifts of a step off the row.
#[derive(Copy, Drop)]
struct Shifts {
    /// `W − 1`.
    last: u8,
    /// `2^(W−1)`, `2^W`, `2^(W+1)`: one row up.
    up_narrow: felt252,
    up: felt252,
    up_wide: felt252,
    /// `2^-(W−1)`, `2^-W`, `2^-(W+1)`: one row down.
    down_narrow: felt252,
    down: felt252,
    down_wide: felt252,
}

#[generate_trait]
pub impl LineImpl of LineTrait {
    /// The tiles strictly between two tiles of the board.
    /// # Arguments
    /// * `self` - The map, any dimensions of the engine
    /// * `from` - The first position, ring tiles included
    /// * `to` - The second position, ring tiles included
    /// # Returns
    /// * `Some` of the bitmap of the tiles of the line between `index_to_hex(from)` and
    ///   `index_to_hex(to)` (`HexTrait::line_to`), both ends excluded (`Some(0)` when they are
    ///   equal or adjacent); `None` when one of those tiles lies outside the board. Symmetric:
    ///   `line(a, b) == line(b, a)`
    /// # Panics
    /// * `'Asserter: position not inside'` if a position is outside the board (`>= W * H`)
    ///
    /// Mirrors nothing in `hexx`: an extension (plan §6.6, N-5).
    fn line(self: HexMap, from: u8, to: u8) -> Option<felt252> {
        // [Check] Both positions inside the board
        LineAssert::assert_inside(self.width, self.height, from, to);
        // [Compute] The table path: the width 15, a distance of at most 6
        if self.width == TABLE_WIDTH {
            if let Some(line) = LineInternal::table(from, to) {
                return line;
            }
        }
        // [Compute] The loop path
        LineInternal::walk(self.width, from, to)
    }

    /// Whether walls block the sight between two tiles: walls block, actors do not, the ends are
    /// not tested (D-24).
    /// # Arguments
    /// * `self` - The map, `1` is walkable
    /// * `from` - The first position
    /// * `to` - The second position
    /// # Returns
    /// * `true` iff `line(from, to)` is `Some(M)` and every tile of `M` is walkable; a line that
    ///   leaves the board blocks the sight (D-27)
    /// # Panics
    /// * `'Asserter: position not inside'` if a position is outside the board
    ///
    /// Mirrors nothing in `hexx`: an extension (plan §6.6, N-5).
    fn line_of_sight(self: HexMap, from: u8, to: u8) -> bool {
        match self.line(from, to) {
            Some(mask) => {
                // [Compute] `M & ~grid == 0`, that is `M & grid == M`, limb by limb
                let mask: u256 = mask.into();
                let grid: u256 = self.grid.into();
                let (low, _, _) = Bits::bitwise(mask.low, grid.low);
                let (high, _, _) = Bits::bitwise(mask.high, grid.high);
                low == mask.low && high == mask.high
            },
            None => false,
        }
    }

    /// The side from which a target is approached along the line.
    /// # Arguments
    /// * `self` - The map
    /// * `from` - The position of origin
    /// * `to` - The target, ring tiles included
    /// # Returns
    /// * The direction, from `to`, of the tile of the line that precedes `to` (`from` itself when
    ///   the line has no tile between them); `None` when `from == to` or when the line leaves the
    ///   board
    /// # Panics
    /// * `'Asserter: position not inside'` if a position is outside the board
    ///
    /// Mirrors nothing in `hexx`: an extension (plan §6.6, N-5).
    fn approach(self: HexMap, from: u8, to: u8) -> Option<Direction> {
        let mask = self.line(from, to)?;
        if from == to {
            return None;
        }
        // [Compute] The tile before `to`: `from` when adjacent, else the one tile of the line
        // among the neighbours of `to` (`neighbor_mask` holds an interior tile only, the ring
        // takes the neighbours one direction at a time)
        let (width, height) = (self.width, self.height);
        let (y, x) = DivRem::div_rem(to, width.try_into().unwrap());
        let previous = if mask == 0 {
            Bits::pow(from)
        } else {
            let around = if x != 0 && y != 0 && x + 1 != width && y + 1 != height {
                let layout = LayoutTrait::new(width, height);
                layout.neighbor_mask(to)
            } else {
                LayoutTrait::edge_neighbors(width, height, to)
            };
            Bits::to_felt(Bits::and(mask.into(), around.into()))
        };
        // [Return] Its direction from `to`
        let (_, odd) = DivRem::div_rem(y, TWO);
        Some(LineInternal::direction(width, to, odd == 1, previous))
    }
}

/// The check of `line`.
#[generate_trait]
impl LineAssert of LineAssertTrait {
    /// Both positions lie in the board, `position < W * H`, for any `u8` dimensions (bounded
    /// integers, the facade's `is_inside`).
    #[feature("bounded-int-utils")]
    #[inline(always)]
    fn assert_inside(width: u8, height: u8, from: u8, to: u8) {
        // [Check] `position − W * H < 0`: the low side of the sign
        let size = mul::<_, _, SizeMul>(width, height);
        let from_inside =
            match constrain::<_, 0, PositionConstrain>(sub::<_, _, PositionSub>(from, size)) {
            Ok(_) => true,
            Err(_) => false,
        };
        let to_inside =
            match constrain::<_, 0, PositionConstrain>(sub::<_, _, PositionSub>(to, size)) {
            Ok(_) => true,
            Err(_) => false,
        };
        assert(from_inside && to_inside, errors::ASSERTER_POSITION_NOT_INSIDE);
    }
}

#[generate_trait]
impl LineInternal of LineInternalTrait {
    /// The table path, on the width 15.
    /// # Arguments
    /// * `from` - The first position, inside the board
    /// * `to` - The second position, inside the board
    /// # Returns
    /// * `Some(line)` when the distance is at most 6, `None` when the loop path must serve the
    ///   pair
    #[inline(always)]
    fn table(from: u8, to: u8) -> Option<Option<felt252>> {
        // [Compute] The key: the difference of the positions and the parity of the row of `from`
        let (_, column) = DivRem::div_rem(from, THIRTY);
        let parity = if column < TABLE_WIDTH {
            0
        } else {
            SPAN
        };
        let key: u32 = (to.into() + OFFSET + parity - from.into()).try_into()?;
        let (relative, lo, hi, lo_to, hi_to) = *LINES.span().get(key)?.unbox();
        // [Return] Every tile in the columns: the mask moved to `from`
        if lo <= column && column <= hi {
            return Some(Some(relative * Bits::pow(from)));
        }
        // [Return] The target in the columns but the line not: the line leaves the board;
        // otherwise the difference is that of a longer line on another row
        if lo_to <= column && column <= hi_to {
            return Some(None);
        }
        None
    }

    /// The loop path: the accumulators of `HexTrait::line_to` on the `Hex` of both positions,
    /// each step a move in one of at most three directions, walked on the board.
    /// # Arguments
    /// * `width` - The width of the map
    /// * `from` - The first position, inside the board
    /// * `to` - The second position, inside the board
    /// # Returns
    /// * The line, `None` as soon as a tile leaves the board (its rows lie between those of the
    ///   ends: only a column can leave)
    fn walk(width: u8, from: u8, to: u8) -> Option<felt252> {
        // [Compute] The ends: `Hex { x: −x − ⌈y/2⌉, y }`
        let divisor: NonZero<u8> = width.try_into().unwrap();
        let (y_from, x_from) = DivRem::div_rem(from, divisor);
        let (y_to, x_to) = DivRem::div_rem(to, divisor);
        let (half_from, odd_from) = DivRem::div_rem(y_from, TWO);
        let (half_to, odd_to) = DivRem::div_rem(y_to, TWO);
        let start: u16 = x_from.into() + half_from.into() + odd_from.into();
        let end: u16 = x_to.into() + half_to.into() + odd_to.into();
        // [Compute] `dx = start − end` is the move of the `Hex`'s `x`, `dy = y_to − y_from`
        let (east, mx) = if start > end {
            (true, start - end)
        } else {
            (false, end - start)
        };
        let (north, my): (bool, u16) = if y_to > y_from {
            (true, (y_to - y_from).into())
        } else {
            (false, (y_from - y_to).into())
        };
        // [Compute] The distance and the three moves: `x` alone, `y` alone, both
        let n = if east == north {
            mx + my
        } else if mx > my {
            mx
        } else {
            my
        };
        let (horizontal, vertical) = (
            if east {
                Direction::East
            } else {
                Direction::West
            },
            if north {
                Direction::NorthEast
            } else {
                Direction::SouthWest
            },
        );
        let both = if east {
            Direction::SouthEast
        } else {
            Direction::NorthWest
        };
        // [Compute] The accumulators of `line_to`: `x` ties toward the larger `x`, `y` toward
        // the smaller `y` (a tie rounds a magnitude down when its start is `N − 1`)
        let (mut ex, mut ey) = (
            if east || n == 0 {
                n
            } else {
                n - 1
            }, if north {
                n - 1
            } else {
                n
            },
        );
        let (ix, iy) = (2 * mx, 2 * my);
        let (tx, ty) = (2 * n - ix, 2 * n - iy);
        // [Compute] The tiles between the ends
        let up = Bits::pow(width);
        let down = Bits::inv(width);
        let shifts = Shifts {
            last: width - 1,
            up_narrow: up * INV_2,
            up,
            up_wide: up + up,
            down_narrow: down + down,
            down,
            down_wide: down * INV_2,
        };
        let mut cursor = Cursor { bit: Bits::pow(from), column: x_from, odd: odd_from == 1 };
        let mut mask: felt252 = 0;
        let mut step: u16 = 1;
        while step < n {
            let moved_x = if ex >= tx {
                ex -= tx;
                true
            } else {
                ex += ix;
                false
            };
            let moved_y = if ey >= ty {
                ey -= ty;
                true
            } else {
                ey += iy;
                false
            };
            let direction = if !moved_y {
                horizontal
            } else if moved_x {
                both
            } else {
                vertical
            };
            if !cursor.advance(@shifts, direction) {
                return None;
            }
            mask += cursor.bit;
            step += 1;
        }
        Some(mask)
    }

    /// The direction from `to` of its neighbour `previous`.
    /// # Arguments
    /// * `width` - The width of the map
    /// * `to` - The position
    /// * `odd` - Whether its row is odd
    /// * `previous` - The bit of one of its board neighbours
    /// # Returns
    /// * The direction, by the offsets of `types::direction`
    fn direction(width: u8, to: u8, odd: bool, previous: felt252) -> Direction {
        let power = Bits::pow(to);
        if previous == power * INV_2 {
            return Direction::East;
        }
        if previous == power + power {
            return Direction::West;
        }
        let up = power * Bits::pow(width);
        let down = power * Bits::inv(width);
        if odd {
            // NorthEast `+W`, NorthWest `+W+1`, SouthWest `−W+1`, SouthEast `−W`
            if previous == up {
                Direction::NorthEast
            } else if previous == up + up {
                Direction::NorthWest
            } else if previous == down + down {
                Direction::SouthWest
            } else {
                Direction::SouthEast
            }
        } else {
            // NorthEast `+W−1`, NorthWest `+W`, SouthWest `−W`, SouthEast `−W−1`
            if previous == up * INV_2 {
                Direction::NorthEast
            } else if previous == up {
                Direction::NorthWest
            } else if previous == down {
                Direction::SouthWest
            } else {
                Direction::SouthEast
            }
        }
    }
}

#[generate_trait]
impl CursorImpl of CursorTrait {
    /// Moves one tile in a direction (the offsets of `types::direction`).
    /// # Arguments
    /// * `self` - The cursor
    /// * `shifts` - The constants of the board
    /// * `direction` - The direction
    /// # Returns
    /// * `false` when the tile lies outside the columns of the board
    #[inline(always)]
    fn advance(ref self: Cursor, shifts: @Shifts, direction: Direction) -> bool {
        let shifts = *shifts;
        match direction {
            Direction::East => {
                if self.column == 0 {
                    return false;
                }
                self.column -= 1;
                self.bit *= INV_2;
            },
            Direction::West => {
                if self.column == shifts.last {
                    return false;
                }
                self.column += 1;
                self.bit += self.bit;
            },
            Direction::NorthEast => {
                if self.odd {
                    self.bit *= shifts.up;
                } else {
                    if self.column == 0 {
                        return false;
                    }
                    self.column -= 1;
                    self.bit *= shifts.up_narrow;
                }
                self.odd = !self.odd;
            },
            Direction::NorthWest => {
                if self.odd {
                    if self.column == shifts.last {
                        return false;
                    }
                    self.column += 1;
                    self.bit *= shifts.up_wide;
                } else {
                    self.bit *= shifts.up;
                }
                self.odd = !self.odd;
            },
            Direction::SouthWest => {
                if self.odd {
                    if self.column == shifts.last {
                        return false;
                    }
                    self.column += 1;
                    self.bit *= shifts.down_narrow;
                } else {
                    self.bit *= shifts.down;
                }
                self.odd = !self.odd;
            },
            Direction::SouthEast => {
                if self.odd {
                    self.bit *= shifts.down;
                } else {
                    if self.column == 0 {
                        return false;
                    }
                    self.column -= 1;
                    self.bit *= shifts.down_wide;
                }
                self.odd = !self.odd;
            },
        }
        true
    }
}

#[cfg(test)]
mod tests {
    // Local imports

    use hexx::board::bits::Bits;
    use hexx::board::direction::Direction;
    use hexx::board::geometry::Geometry;
    use hexx::board::layout::LayoutTrait;
    use hexx::board::map::HexMap;
    use hexx::hex::{Hex, HexTrait};
    use super::{LineInternal, LineTrait};

    /// Every tile of 15 × 16 walkable: 2^240 − 1.
    const OPEN_15X16: felt252 = 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff;
    /// The window of the game.
    const WIDTH: u8 = 15;
    const HEIGHT: u8 = 16;
    /// The six directions, in index order.
    const DIRECTIONS: [Direction; 6] = [
        Direction::East, Direction::NorthEast, Direction::NorthWest, Direction::West,
        Direction::SouthWest, Direction::SouthEast,
    ];

    // Oracles

    #[generate_trait]
    impl Oracle of OracleTrait {
        /// The board's `line` by its definition (plan §6.6): the mirror's `line_to` between the
        /// `Hex` of both positions, each tile between the ends back on the board, `None` as soon
        /// as one leaves it.
        fn line(width: u8, height: u8, from: u8, to: u8) -> Option<felt252> {
            let line = Geometry::index_to_hex(width, from)
                .line_to(Geometry::index_to_hex(width, to));
            let mut mask: felt252 = 0;
            let mut i: u32 = 1;
            while i + 1 < line.len() {
                let position = Geometry::hex_to_index(width, height, *line.at(i))?;
                mask += Bits::pow(position);
                i += 1;
            }
            Some(mask)
        }

        /// `line_of_sight` by a per-tile scalar walk: every tile between the ends, a tile off the
        /// board blocks, a wall blocks.
        fn sight(width: u8, height: u8, grid: felt252, from: u8, to: u8) -> bool {
            let line = Geometry::index_to_hex(width, from)
                .line_to(Geometry::index_to_hex(width, to));
            let grid: u256 = grid.into();
            let mut i: u32 = 1;
            while i + 1 < line.len() {
                match Geometry::hex_to_index(width, height, *line.at(i)) {
                    Some(position) => { if !Bits::get(grid, position) {
                        return false;
                    } },
                    None => { return false; },
                }
                i += 1;
            }
            true
        }

        /// `approach` by the last ordered sample of the scalar line: the direction from `to` of
        /// the element that precedes it, `None` when `from == to` or the line leaves the board.
        fn approach(width: u8, height: u8, from: u8, to: u8) -> Option<Direction> {
            if from == to {
                return None;
            }
            Self::line(width, height, from, to)?;
            let line = Geometry::index_to_hex(width, from)
                .line_to(Geometry::index_to_hex(width, to));
            let previous = *line.at(line.len() - 2);
            let previous = Geometry::hex_to_index(width, height, previous).unwrap();
            LayoutTrait::neighbor_direction(width, height, to, previous)
        }

        /// Whether a position lies on the ring of the board.
        fn ring(width: u8, height: u8, position: u8) -> bool {
            let (x, y) = LayoutTrait::coords(width, position);
            x == 0 || y == 0 || x == width - 1 || y == height - 1
        }

        /// The next state of a 64-bit linear congruential generator (Knuth's MMIX constants).
        fn next(state: u64) -> u64 {
            let product: u128 = state.into() * 6364136223846793005 + 1442695040888963407;
            (product % 0x10000000000000000).try_into().unwrap()
        }

        /// A position of a board of `size` tiles drawn from a state.
        fn draw(state: u64, shift: u64, size: u16) -> u8 {
            let size: u64 = size.into();
            ((state / shift) % size).try_into().unwrap()
        }

        /// A map with no seed.
        fn map(width: u8, height: u8, grid: felt252) -> HexMap {
            HexMap { width, height, grid, seed: 0 }
        }

        /// The position of the tile `(x, y)`.
        fn at(width: u8, x: u8, y: u8) -> u8 {
            LayoutTrait::index(width, x, y)
        }
    }

    // Regression cases (plan §6.6)

    /// R-N5-1: on a 7 × 7, the tied midpoint of `(0, 0) → (0, 2)` is `(−1, 1)`, off the board.
    #[test]
    #[available_gas(l2_gas: 76671)]
    fn test_line_regression_r_n5_1() {
        let map = Oracle::map(7, 7, LayoutTrait::interior(7, 7));
        let (from, to) = (Oracle::at(7, 0, 0), Oracle::at(7, 0, 2));
        assert!(map.line(from, to).is_none());
        assert!(map.line(to, from).is_none());
        assert!(!map.line_of_sight(from, to));
        assert!(map.approach(from, to).is_none());
    }

    /// R-N5-2: on a 7 × 7, `(3, 3) → (3, 5)` has the single tile `(3, 4)`, index 31 (not 39).
    #[test]
    #[available_gas(l2_gas: 29873)]
    fn test_line_regression_r_n5_2() {
        let map = Oracle::map(7, 7, 0);
        let (from, to) = (Oracle::at(7, 3, 3), Oracle::at(7, 3, 5));
        assert!(map.line(from, to) == Some(0x80000000));
        assert!(map.line(to, from) == Some(0x80000000));
    }

    /// R-N5-3: on 15 × 16, `(0, 0) → (14, 15)` has 21 tiles between its ends and
    /// `(1, 14) → (13, 1)` has 18.
    #[test]
    #[available_gas(l2_gas: 340616)]
    fn test_line_regression_r_n5_3() {
        let map = Oracle::map(WIDTH, HEIGHT, 0);
        let line: u256 = map
            .line(Oracle::at(WIDTH, 0, 0), Oracle::at(WIDTH, 14, 15))
            .unwrap()
            .into();
        assert!(Bits::popcount(line) == 21);
        let line: u256 = map
            .line(Oracle::at(WIDTH, 1, 14), Oracle::at(WIDTH, 13, 1))
            .unwrap()
            .into();
        assert!(Bits::popcount(line) == 18);
    }

    /// R-N5-4: on 15 × 16, the predecessor of the ring target `(10, 15)` from `(7, 9)` is
    /// `(10, 14)`, its `SouthEast` neighbour (`i − W` on the odd row 15).
    #[test]
    #[available_gas(l2_gas: 100421)]
    fn test_line_regression_r_n5_4() {
        let map = Oracle::map(WIDTH, HEIGHT, 0);
        let (from, to) = (Oracle::at(WIDTH, 7, 9), Oracle::at(WIDTH, 10, 15));
        assert!(map.approach(from, to) == Some(Direction::SouthEast));
        let line: u256 = map.line(from, to).unwrap().into();
        assert!(Bits::get(line, Oracle::at(WIDTH, 10, 14)));
    }

    /// The ends: a tile with itself and two neighbours have nothing between them; `approach` is
    /// `None` on a tile with itself, and the direction of `from` seen from `to` on neighbours.
    #[test]
    #[available_gas(l2_gas: 273243183)]
    fn test_line_ends() {
        let boards: [(u8, u8); 3] = [(7, 7), (15, 16), (17, 14)];
        for (width, height) in boards.span() {
            let (width, height) = (*width, *height);
            let map = Oracle::map(width, height, 0);
            let mut from: u8 = 0;
            while from != width * height {
                assert!(map.line(from, from) == Some(0));
                assert!(map.approach(from, from).is_none());
                assert!(map.line_of_sight(from, from));
                for direction in DIRECTIONS.span() {
                    if let Some(to) = LayoutTrait::neighbor(width, height, from, *direction) {
                        assert!(map.line(from, to) == Some(0));
                        let back = LayoutTrait::neighbor_direction(width, height, to, from);
                        assert!(map.approach(from, to) == back);
                    }
                }
                from += 1;
            }
        }
    }

    /// A position outside the board panics, on either end, in each function.
    #[test]
    #[available_gas(l2_gas: 8201)]
    #[should_panic(expected: 'Asserter: position not inside')]
    fn test_line_revert_from_outside() {
        Oracle::map(WIDTH, HEIGHT, 0).line(240, 0);
    }

    #[test]
    #[available_gas(l2_gas: 8201)]
    #[should_panic(expected: 'Asserter: position not inside')]
    fn test_line_revert_to_outside() {
        Oracle::map(7, 7, 0).line(0, 49);
    }

    #[test]
    #[available_gas(l2_gas: 8201)]
    #[should_panic(expected: 'Asserter: position not inside')]
    fn test_line_of_sight_revert_outside() {
        Oracle::map(WIDTH, HEIGHT, 0).line_of_sight(0, 255);
    }

    #[test]
    #[available_gas(l2_gas: 8201)]
    #[should_panic(expected: 'Asserter: position not inside')]
    fn test_line_approach_revert_outside() {
        Oracle::map(WIDTH, HEIGHT, 0).approach(250, 0);
    }

    // The table against the loop: every pair within distance 6 of 15 × 16, from every position
    // (both parities); beyond it, the table serves nothing

    #[generate_trait]
    impl Check of CheckTrait {
        fn table(first: u8, last: u8) {
            let mut from = first;
            while from != last {
                let mut to: u8 = 0;
                while to != 240 {
                    let table = LineInternal::table(from, to);
                    if Geometry::distance(WIDTH, from, to) <= 6 {
                        let walk = LineInternal::walk(WIDTH, from, to);
                        assert!(table == Some(walk), "{} {}", from, to);
                    } else {
                        assert!(table.is_none(), "{} {}", from, to);
                    }
                    to += 1;
                }
                from += 1;
            }
        }

        /// `line(a, b) == line(b, a)` on every ordered pair from `first..last`, `None` included.
        fn symmetry(width: u8, height: u8, first: u8, last: u8) {
            let map = Oracle::map(width, height, 0);
            let size = width * height;
            let mut from = first;
            while from != last {
                let mut to = from + 1;
                while to != size {
                    assert!(map.line(from, to) == map.line(to, from), "{} {}", from, to);
                    to += 1;
                }
                from += 1;
            }
        }

        /// `approach` against the oracle, every `from` of 15 × 16 and the ring targets of rank
        /// `first..last` (the 58 ring tiles in index order).
        fn approach(first: u8, last: u8) {
            let map = Oracle::map(WIDTH, HEIGHT, 0);
            let mut rank: u8 = 0;
            let mut to: u8 = 0;
            while to != 240 {
                if Oracle::ring(WIDTH, HEIGHT, to) {
                    if first <= rank && rank < last {
                        let mut from: u8 = 0;
                        while from != 240 {
                            let expected = Oracle::approach(WIDTH, HEIGHT, from, to);
                            assert!(map.approach(from, to) == expected, "{} {}", from, to);
                            from += 1;
                        }
                    }
                    rank += 1;
                }
                to += 1;
            }
        }

        /// `line_of_sight` against the scalar walk on every ordered pair of 7 × 7.
        fn sight_7x7(grid: felt252) {
            let map = Oracle::map(7, 7, grid);
            let mut from: u8 = 0;
            while from != 49 {
                let mut to: u8 = 0;
                while to != 49 {
                    let expected = Oracle::sight(7, 7, grid, from, to);
                    assert!(map.line_of_sight(from, to) == expected, "{} {}", from, to);
                    to += 1;
                }
                from += 1;
            }
        }
    }

    #[test]
    #[available_gas(l2_gas: 496049904)]
    fn test_line_table_0() {
        Check::table(0, 60);
    }

    #[test]
    #[available_gas(l2_gas: 601189943)]
    fn test_line_table_1() {
        Check::table(60, 120);
    }

    #[test]
    #[available_gas(l2_gas: 601217442)]
    fn test_line_table_2() {
        Check::table(120, 180);
    }

    #[test]
    #[available_gas(l2_gas: 496905728)]
    fn test_line_table_3() {
        Check::table(180, 240);
    }

    // Symmetry, every ordered pair of 7 × 7 and of 15 × 16

    #[test]
    #[available_gas(l2_gas: 128890629)]
    fn test_line_symmetry_7x7() {
        Check::symmetry(7, 7, 0, 49);
    }

    #[test]
    #[available_gas(l2_gas: 771452241)]
    fn test_line_symmetry_15x16_0() {
        Check::symmetry(WIDTH, HEIGHT, 0, 16);
    }

    #[test]
    #[available_gas(l2_gas: 724851194)]
    fn test_line_symmetry_15x16_1() {
        Check::symmetry(WIDTH, HEIGHT, 16, 33);
    }

    #[test]
    #[available_gas(l2_gas: 650807000)]
    fn test_line_symmetry_15x16_2() {
        Check::symmetry(WIDTH, HEIGHT, 33, 51);
    }

    #[test]
    #[available_gas(l2_gas: 614142858)]
    fn test_line_symmetry_15x16_3() {
        Check::symmetry(WIDTH, HEIGHT, 51, 71);
    }

    #[test]
    #[available_gas(l2_gas: 589036256)]
    fn test_line_symmetry_15x16_4() {
        Check::symmetry(WIDTH, HEIGHT, 71, 93);
    }

    #[test]
    #[available_gas(l2_gas: 515229509)]
    fn test_line_symmetry_15x16_5() {
        Check::symmetry(WIDTH, HEIGHT, 93, 120);
    }

    #[test]
    #[available_gas(l2_gas: 449034905)]
    fn test_line_symmetry_15x16_6() {
        Check::symmetry(WIDTH, HEIGHT, 120, 155);
    }

    #[test]
    #[available_gas(l2_gas: 360507021)]
    fn test_line_symmetry_15x16_7() {
        Check::symmetry(WIDTH, HEIGHT, 155, 239);
    }

    // `line` against the scalar oracle: every pair of 7 × 7, seeded pairs of 15 × 16, of the
    // longest boards and of 19 × 13

    #[test]
    #[available_gas(l2_gas: 350694845)]
    fn test_line_oracle_7x7() {
        let map = Oracle::map(7, 7, 0);
        let mut from: u8 = 0;
        while from != 49 {
            let mut to: u8 = 0;
            while to != 49 {
                assert!(map.line(from, to) == Oracle::line(7, 7, from, to), "{} {}", from, to);
                to += 1;
            }
            from += 1;
        }
    }

    #[test]
    #[available_gas(l2_gas: 196126665)]
    fn test_line_oracle_seeded() {
        let boards: [(u8, u8, u32); 4] = [(15, 16, 256), (83, 3, 64), (3, 83, 64), (19, 13, 128)];
        let mut state: u64 = 'line';
        for (width, height, pairs) in boards.span() {
            let (width, height) = (*width, *height);
            let map = Oracle::map(width, height, 0);
            let size: u16 = width.into() * height.into();
            let mut index: u32 = 0;
            while index != *pairs {
                state = Oracle::next(state);
                let from = Oracle::draw(state, 0x100000000, size);
                let to = Oracle::draw(state, 0x10000000000, size);
                assert!(map.line(from, to) == Oracle::line(width, height, from, to));
                index += 1;
            }
        }
    }

    // `line_of_sight` against the per-tile scalar walk

    #[test]
    #[available_gas(l2_gas: 381276981)]
    fn test_line_of_sight_7x7_interior() {
        Check::sight_7x7(LayoutTrait::interior(7, 7));
    }

    #[test]
    #[available_gas(l2_gas: 351428435)]
    fn test_line_of_sight_7x7_seeded() {
        Check::sight_7x7(0x1b5ed3a96f7b5);
    }

    #[test]
    #[available_gas(l2_gas: 328969478)]
    fn test_line_of_sight_7x7_walls() {
        Check::sight_7x7(0);
    }

    #[test]
    #[available_gas(l2_gas: 136714721)]
    fn test_line_of_sight_seeded() {
        let grids: [felt252; 2] = [
            0x5dd3f0fde6ffdc6f7eef1e26adb45cd635e61877e53defbfc1fd2efafee7, OPEN_15X16,
        ];
        let mut state: u64 = 'sight';
        for grid in grids.span() {
            let map = Oracle::map(WIDTH, HEIGHT, *grid);
            let mut index: u32 = 0;
            while index != 256 {
                state = Oracle::next(state);
                let from = Oracle::draw(state, 0x100000000, 240);
                let to = Oracle::draw(state, 0x10000000000, 240);
                let expected = Oracle::sight(WIDTH, HEIGHT, *grid, from, to);
                assert!(map.line_of_sight(from, to) == expected, "{} {}", from, to);
                index += 1;
            }
        }
    }

    // `approach` against the last ordered sample of the scalar line, every pair of 15 × 16 with
    // `to` on the ring

    #[test]
    #[available_gas(l2_gas: 732552261)]
    fn test_line_approach_ring_0() {
        Check::approach(0, 6);
    }

    #[test]
    #[available_gas(l2_gas: 674586948)]
    fn test_line_approach_ring_1() {
        Check::approach(6, 12);
    }

    #[test]
    #[available_gas(l2_gas: 757866659)]
    fn test_line_approach_ring_2() {
        Check::approach(12, 18);
    }

    #[test]
    #[available_gas(l2_gas: 712287887)]
    fn test_line_approach_ring_3() {
        Check::approach(18, 24);
    }

    #[test]
    #[available_gas(l2_gas: 685095651)]
    fn test_line_approach_ring_4() {
        Check::approach(24, 30);
    }

    #[test]
    #[available_gas(l2_gas: 688874609)]
    fn test_line_approach_ring_5() {
        Check::approach(30, 36);
    }

    #[test]
    #[available_gas(l2_gas: 737762611)]
    fn test_line_approach_ring_6() {
        Check::approach(36, 42);
    }

    #[test]
    #[available_gas(l2_gas: 741373448)]
    fn test_line_approach_ring_7() {
        Check::approach(42, 48);
    }

    #[test]
    #[available_gas(l2_gas: 679227003)]
    fn test_line_approach_ring_8() {
        Check::approach(48, 54);
    }

    #[test]
    #[available_gas(l2_gas: 512468410)]
    fn test_line_approach_ring_9() {
        Check::approach(54, 58);
    }

    /// `approach` on seeded pairs of 15 × 16 and 17 × 14, interior targets mostly.
    #[test]
    #[available_gas(l2_gas: 216729614)]
    fn test_line_approach_seeded() {
        let boards: [(u8, u8); 2] = [(15, 16), (17, 14)];
        let mut state: u64 = 'approach';
        for (width, height) in boards.span() {
            let (width, height) = (*width, *height);
            let map = Oracle::map(width, height, 0);
            let size: u16 = width.into() * height.into();
            let mut index: u32 = 0;
            while index != 256 {
                state = Oracle::next(state);
                let from = Oracle::draw(state, 0x100000000, size);
                let to = Oracle::draw(state, 0x10000000000, size);
                let expected = Oracle::approach(width, height, from, to);
                assert!(map.approach(from, to) == expected, "{} {}", from, to);
                index += 1;
            }
        }
    }

    // Benchmarks, on the worst cases of plan §6.6: the difference between a test that calls twice
    // and one that calls once, the method of `bench_assembly`.

    #[derive(Copy, Drop)]
    struct Bench {
        /// The table case: from `(7, 7)` to `(3, 10)` (`Δ = (3, 3)` in the mirror frame, distance
        /// 6, ties at the steps 1, 3 and 5), then to `(12, 4)` (`Δ = (−3, −3)`).
        table: [(u8, u8); 2],
        /// The longest line of 15 × 16, `(0, 0) → (14, 15)` (22 steps), both ways.
        board: [(u8, u8); 2],
        /// The longest line between interior tiles, `(1, 14) → (13, 1)` (19 steps), both ways.
        interior: [(u8, u8); 2],
        /// The diameter of 83 × 3, `(0, 0) → (82, 2)` (83 steps), both ways.
        wide: [(u8, u8); 2],
        /// Ring targets at distance 6: `(7, 9) → (10, 15)` (R-N5-4) and `(7, 6) → (4, 0)`.
        ring: [(u8, u8); 2],
        /// The mirror: `Δ = (11, 11)`, 22 steps with a tie at every odd step.
        hexes: [(Hex, Hex); 2],
    }

    #[generate_trait]
    impl Inputs of InputsTrait {
        /// The inputs, opaque to the compiler (`#[inline(never)]`, as in `bench_assembly`).
        #[inline(never)]
        fn get() -> Bench {
            Bench {
                table: [(112, 153), (112, 72)],
                board: [(0, 239), (239, 0)],
                interior: [(211, 28), (28, 211)],
                wide: [(0, 248), (248, 0)],
                ring: [(142, 235), (97, 4)],
                hexes: [
                    (Hex { x: 0, y: 0 }, Hex { x: 11, y: 11 }),
                    (Hex { x: 5, y: -3 }, Hex { x: 16, y: 8 }),
                ],
            }
        }
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 21273)]
    fn bench_line_table_once() {
        let bench = Inputs::get();
        let [(from, to), _] = bench.table;
        assert!(Oracle::map(WIDTH, HEIGHT, 0).line(from, to).is_some());
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 32981)]
    fn bench_line_table_twice() {
        let bench = Inputs::get();
        let [(from, to), (other, next)] = bench.table;
        let map = Oracle::map(WIDTH, HEIGHT, 0);
        assert!(map.line(from, to).is_some());
        assert!(map.line(other, next).is_some());
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 30184)]
    fn bench_line_of_sight_table_once() {
        let bench = Inputs::get();
        let [(from, to), _] = bench.table;
        assert!(Oracle::map(WIDTH, HEIGHT, OPEN_15X16).line_of_sight(from, to));
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 48775)]
    fn bench_line_of_sight_table_twice() {
        let bench = Inputs::get();
        let [(from, to), (other, next)] = bench.table;
        let map = Oracle::map(WIDTH, HEIGHT, OPEN_15X16);
        assert!(map.line_of_sight(from, to));
        assert!(map.line_of_sight(other, next));
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 227199)]
    fn bench_line_loop_board_once() {
        let bench = Inputs::get();
        let [(from, to), _] = bench.board;
        assert!(Oracle::map(WIDTH, HEIGHT, 0).line(from, to).is_some());
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 440213)]
    fn bench_line_loop_board_twice() {
        let bench = Inputs::get();
        let [(from, to), (other, next)] = bench.board;
        let map = Oracle::map(WIDTH, HEIGHT, 0);
        assert!(map.line(from, to).is_some());
        assert!(map.line(other, next).is_some());
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 202608)]
    fn bench_line_loop_interior_once() {
        let bench = Inputs::get();
        let [(from, to), _] = bench.interior;
        assert!(Oracle::map(WIDTH, HEIGHT, 0).line(from, to).is_some());
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 393278)]
    fn bench_line_loop_interior_twice() {
        let bench = Inputs::get();
        let [(from, to), (other, next)] = bench.interior;
        let map = Oracle::map(WIDTH, HEIGHT, 0);
        assert!(map.line(from, to).is_some());
        assert!(map.line(other, next).is_some());
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 733425)]
    fn bench_line_loop_wide_once() {
        let bench = Inputs::get();
        let [(from, to), _] = bench.wide;
        assert!(Oracle::map(83, 3, 0).line(from, to).is_some());
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 1432536)]
    fn bench_line_loop_wide_twice() {
        let bench = Inputs::get();
        let [(from, to), (other, next)] = bench.wide;
        let map = Oracle::map(83, 3, 0);
        assert!(map.line(from, to).is_some());
        assert!(map.line(other, next).is_some());
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 53053)]
    fn bench_line_approach_interior_once() {
        let bench = Inputs::get();
        let [(from, to), _] = bench.table;
        assert!(Oracle::map(WIDTH, HEIGHT, 0).approach(from, to).is_some());
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 93421)]
    fn bench_line_approach_interior_twice() {
        let bench = Inputs::get();
        let [(from, to), (other, next)] = bench.table;
        let map = Oracle::map(WIDTH, HEIGHT, 0);
        assert!(map.approach(from, to).is_some());
        assert!(map.approach(other, next).is_some());
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 104240)]
    fn bench_line_approach_ring_once() {
        let bench = Inputs::get();
        let [(from, to), _] = bench.ring;
        assert!(Oracle::map(WIDTH, HEIGHT, 0).approach(from, to) == Some(Direction::SouthEast));
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 194589)]
    fn bench_line_approach_ring_twice() {
        let bench = Inputs::get();
        let [(from, to), (other, next)] = bench.ring;
        let map = Oracle::map(WIDTH, HEIGHT, 0);
        assert!(map.approach(from, to) == Some(Direction::SouthEast));
        assert!(map.approach(other, next).is_some());
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 187467)]
    fn bench_line_to_once() {
        let bench = Inputs::get();
        let [(a, b), _] = bench.hexes;
        assert!(a.line_to(b).len() == 23);
    }

    #[test]
    #[inline(never)]
    #[available_gas(l2_gas: 365159)]
    fn bench_line_to_twice() {
        let bench = Inputs::get();
        let [(a, b), (c, d)] = bench.hexes;
        assert!(a.line_to(b).len() == 23);
        assert!(c.line_to(d).len() == 23);
    }
}
