//! What every generator shares: the seeded generator, the probe of a `hexx` call that may panic,
//! and the emitter of Cairo test functions with their budgets.

use std::panic::{catch_unwind, set_hook, AssertUnwindSafe};
use std::sync::Once;

use crate::spec::Spec;

/// xorshift32, seeded by an FNV-1a hash of `seed`: integer-only, deterministic across hosts (no
/// float, no platform RNG) — the same convention the house `refgen` (`glam-cairo`) uses for its
/// own PRNG, at a scale the mirror's integer functions need.
pub struct Rng(u32);

impl Rng {
    pub fn new(seed: &str) -> Self {
        let mut hash: u32 = 0x811c9dc5;
        for byte in seed.bytes() {
            hash ^= u32::from(byte);
            hash = hash.wrapping_mul(0x0100_0193);
        }
        Self(if hash == 0 { 1 } else { hash })
    }

    fn next_u32(&mut self) -> u32 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 17;
        self.0 ^= self.0 << 5;
        self.0
    }

    /// Uniform in `[min, max]` inclusive.
    pub fn next_i32(&mut self, min: i32, max: i32) -> i32 {
        let span = (i64::from(max) - i64::from(min) + 1) as u32;
        (i64::from(min) + i64::from(self.next_u32() % span)) as i32
    }
}

/// `count` seeded points of `[min, max]²`.
pub fn seeded_points(seed: &str, count: usize, min: i32, max: i32) -> Vec<(i32, i32)> {
    let mut rng = Rng::new(seed);
    (0..count).map(|_| (rng.next_i32(min, max), rng.next_i32(min, max))).collect()
}

/// The `i32` values near the bounds where `hexx` wraps in a release build and this port panics
/// (plan §3.1): the extremes, their neighbours, the halves (where `x + y` and `x - y` cross the
/// bounds) and the values around zero.
pub const BOUND_VALUES: [i32; 11] = [
    i32::MIN,
    i32::MIN + 1,
    -1_073_741_825,
    -1_073_741_824,
    -1,
    0,
    1,
    1_073_741_823,
    1_073_741_824,
    i32::MAX - 1,
    i32::MAX,
];

/// Every pair of `BOUND_VALUES`: 121 points, `x` outermost.
pub fn bound_points() -> Vec<(i32, i32)> {
    BOUND_VALUES.iter().flat_map(|&x| BOUND_VALUES.iter().map(move |&y| (x, y))).collect()
}

static QUIET: Once = Once::new();

/// Runs `f` and returns `None` if it panicked. `refgen` is built with `overflow-checks = true` in
/// every profile (`Cargo.toml`), so an `i32` operation of `hexx` that leaves its range panics and
/// is reported here, whatever the profile of the run.
pub fn probe<T>(f: impl FnOnce() -> T) -> Option<T> {
    QUIET.call_once(|| set_hook(Box::new(|_| {})));
    catch_unwind(AssertUnwindSafe(f)).ok()
}

/// Every `i`-th of `count` elements of `items`, evenly spaced, the first and the last included:
/// the deterministic pick of the panicking cases that get a `#[should_panic]` test of their own.
pub fn spread<T: Clone>(items: &[T], count: usize) -> Vec<T> {
    if items.len() <= count {
        return items.to_vec();
    }
    (0..count).map(|i| items[i * (items.len() - 1) / (count - 1).max(1)].clone()).collect()
}

/// The text of a generated golden file and the names of its tests.
pub struct Emitter<'a> {
    spec: &'a Spec,
    pub out: String,
    pub tests: Vec<String>,
}

impl<'a> Emitter<'a> {
    pub fn new(spec: &'a Spec, oracle: &str, uses: &str) -> Self {
        let module = &spec.module;
        let mut out = String::new();
        out.push_str(&format!(
            "// Generated by `cargo run --manifest-path tools/refgen/Cargo.toml -- gen {module}`.\n"
        ));
        out.push_str(&format!("// Do not edit by hand; edit tools/refgen/specs/{module}.toml instead.\n"));
        out.push_str("//\n");
        out.push_str(&format!("// Oracle: hexx 0.25.0, {oracle}\n"));
        out.push_str("// (pinned checkout sources/hexx, tag 0.25.0,\n");
        out.push_str("// commit b6b9afb1a6d413817509d00ce9ec6b9d52339a7c).\n");
        out.push_str("//\n");
        out.push_str("// Budgets: `gas.<test>` keys of the spec, ceil(1.05 * measured).\n\n");
        out.push_str(uses);
        out.push('\n');
        Self { spec, out, tests: Vec::new() }
    }

    /// One test function: `body` is the lines of the function, already indented by four spaces.
    pub fn test(&mut self, name: &str, should_panic: bool, body: &str) -> Result<(), String> {
        let gas = self.spec.gas(name)?;
        self.out.push_str("\n#[test]\n");
        self.out.push_str(&format!("#[available_gas(l2_gas: {gas})]\n"));
        if should_panic {
            self.out.push_str("#[should_panic]\n");
        }
        self.out.push_str(&format!("fn {name}() {{\n{body}}}\n"));
        self.tests.push(name.to_string());
        Ok(())
    }

    /// The check that no `gas.<test>` key of the spec names a test that was not generated.
    pub fn finish(self) -> Result<String, String> {
        for stale in self.spec.budgeted_tests() {
            if !self.tests.contains(&stale) {
                return Err(format!(
                    "specs/{}.toml: `gas.{stale}` names no generated test",
                    self.spec.module
                ));
            }
        }
        Ok(self.out)
    }
}

/// `array![...]` of tuples typed `Array<(types)>`, packed as `scarb fmt` packs them (as many
/// tuples per line as fit in 100 columns, each line ending with a comma), so that the generated
/// file is stable under `scarb fmt --check`.
pub fn cases_array(types: &str, rows: &[String]) -> String {
    let mut out = format!("    let cases: Array<({types})> = array![\n");
    let mut line = String::new();
    for row in rows {
        let item = format!("({row})");
        if line.is_empty() {
            line = format!("        {item},");
        } else if line.len() + 1 + item.len() + 1 <= 100 {
            line.push_str(&format!(" {item},"));
        } else {
            out.push_str(&line);
            out.push('\n');
            line = format!("        {item},");
        }
    }
    if !line.is_empty() {
        out.push_str(&line);
        out.push('\n');
    }
    out.push_str("    ];\n");
    out
}
