//! `refgen`: golden-vector generator. `hexx` 0.25.0 is the oracle of the Cairo port (plan §4.3).
//!
//! ```text
//! cargo run --manifest-path tools/refgen/Cargo.toml -- gen [module]     # write the file(s)
//! cargo run --manifest-path tools/refgen/Cargo.toml -- check [module]   # CI: exit 1 on drift
//! ```
//!
//! Dependency-free by design (no `toml`/`serde`, mirroring the Python scripts' own house rule):
//! `specs/*.toml` here is a deliberately small, flat format (`key = value` lines and
//! `[[function]]` blocks, no nesting), parsed by `spec::load` without an external crate.

mod spec;

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use hexx::Hex;

use spec::Spec;

const USAGE: &str = "usage: refgen [--root <repo>] [--specs <dir>] <gen|check> [module]";

fn default_specs_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("specs")
}

fn default_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("..")
}

/// xorshift32, seeded by an FNV-1a hash of `seed`: integer-only, deterministic across hosts (no
/// float, no platform RNG) — the same convention the house `refgen` (`glam-cairo`) uses for its
/// own PRNG, at a scale this package's single function needs.
struct Rng(u32);

impl Rng {
    fn new(seed: &str) -> Self {
        let mut hash: u32 = 0x811c9dc5;
        for byte in seed.bytes() {
            hash ^= u32::from(byte);
            hash = hash.wrapping_mul(0x0100_0193);
        }
        Self(if hash == 0 { 1 } else { hash })
    }

    fn next_u32(&mut self) -> u32 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 17;
        self.0 ^= self.0 << 5;
        self.0
    }

    /// Uniform in `[min, max]` inclusive.
    fn next_i32(&mut self, min: i32, max: i32) -> i32 {
        let span = (max - min + 1) as u32;
        min + (self.next_u32() % span) as i32
    }
}

/// One `Hex::distance_to` golden case: two coordinates and the real `hexx` result.
struct Case {
    x1: i32,
    y1: i32,
    x2: i32,
    y2: i32,
    expected: i32,
}

fn distance_to_cases(function: &spec::Function) -> Vec<Case> {
    let mut rng = Rng::new(&function.seed);
    (0..function.samples)
        .map(|_| {
            let x1 = rng.next_i32(function.domain_min, function.domain_max);
            let y1 = rng.next_i32(function.domain_min, function.domain_max);
            let x2 = rng.next_i32(function.domain_min, function.domain_max);
            let y2 = rng.next_i32(function.domain_min, function.domain_max);
            let expected = Hex::new(x1, y1).distance_to(Hex::new(x2, y2));
            Case { x1, y1, x2, y2, expected }
        })
        .collect()
}

fn emit_hex_module(spec: &Spec) -> Result<String, String> {
    let function = spec
        .functions
        .iter()
        .find(|f| f.name == "distance_to")
        .ok_or_else(|| "specs/hex.toml: no [[function]] named distance_to".to_string())?;
    let cases = distance_to_cases(function);

    let mut out = String::new();
    out.push_str("// Generated by `cargo run --manifest-path tools/refgen/Cargo.toml -- gen hex`.\n");
    out.push_str("// Do not edit by hand; edit tools/refgen/specs/hex.toml instead.\n");
    out.push_str("//\n");
    out.push_str("// Oracle: hexx 0.25.0, `Hex::distance_to` (src/hex/mod.rs:615, pinned checkout\n");
    out.push_str("// sources/hexx, tag 0.25.0, commit b6b9afb1a6d413817509d00ce9ec6b9d52339a7c).\n");
    out.push_str("//\n");
    out.push_str("// Kept out of the build until M1-T2 ports `Hex` and `HexTrait::distance_to`\n");
    out.push_str("// (plan §4.3, brief LIB-04 scope 4): staged here, not under crates/hexx/tests/,\n");
    out.push_str("// so scarb never compiles it before then. `tools/refgen/README.md` says why and\n");
    out.push_str("// how CI checks it is current without a Rust toolchain in the main job.\n\n");
    out.push_str("use hexx::hex::{Hex, HexTrait, hex};\n\n");
    out.push_str("#[test]\n");
    out.push_str("fn golden_hex_distance_to() {\n");
    out.push_str("    let cases: Array<(i32, i32, i32, i32, i32)> = array![\n");
    for c in &cases {
        out.push_str(&format!(
            "        ({}, {}, {}, {}, {}),\n",
            c.x1, c.y1, c.x2, c.y2, c.expected
        ));
    }
    out.push_str("    ];\n");
    out.push_str("    let mut i = 0;\n");
    out.push_str("    while i < cases.len() {\n");
    out.push_str("        let (x1, y1, x2, y2, expected) = *cases.at(i);\n");
    out.push_str("        let a = hex(x1, y1);\n");
    out.push_str("        let b = hex(x2, y2);\n");
    out.push_str("        assert(a.distance_to(b) == expected, 'distance_to mismatch');\n");
    out.push_str("        i += 1;\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    Ok(out)
}

/// `tools/refgen/generated/`, not `crates/<package>/tests/`: confirmed empirically (see
/// `tools/refgen/README.md`) that Scarb bundles every `.cairo` file directly under a package's
/// `tests/` into one `<package>_integrationtest` target even with no `tests/lib.cairo` present,
/// so a golden file for a function the mirror does not have yet (`distance_to`, before M1-T2)
/// would break `scarb build` / `snforge test` the moment it exists there. LIB-05 (M1-T2) moves
/// the file into `crates/<package>/tests/` and wires it into a `tests/lib.cairo` once the
/// mirror item lands — that is what "kept out of the build" means here (plan §4.3, brief
/// LIB-04 scope 4).
fn target(root: &Path, spec: &Spec) -> PathBuf {
    root.join("tools").join("refgen").join("generated").join(format!("golden_{}.cairo", spec.module))
}

fn load_specs(dir: &Path, filter: &[String]) -> Result<Vec<Spec>, String> {
    let mut paths: Vec<PathBuf> = fs::read_dir(dir)
        .map_err(|e| format!("{}: {e}", dir.display()))?
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|e| e == "toml"))
        .collect();
    paths.sort();
    let specs: Result<Vec<Spec>, String> = paths.iter().map(|p| Spec::load(p)).collect();
    let mut specs = specs?;
    for module in filter {
        if !specs.iter().any(|s| &s.module == module) {
            return Err(format!("no spec {}/{module}.toml", dir.display()));
        }
    }
    if !filter.is_empty() {
        specs.retain(|s| filter.contains(&s.module));
    }
    Ok(specs)
}

fn run() -> Result<bool, String> {
    let mut args: Vec<String> = env::args().skip(1).collect();
    let mut root = default_root();
    let mut specs_dir = default_specs_dir();
    loop {
        match args.first().map(String::as_str) {
            Some("--specs") if args.len() >= 2 => {
                specs_dir = PathBuf::from(args[1].clone());
                args.drain(..2);
            }
            Some("--root") if args.len() >= 2 => {
                root = PathBuf::from(args[1].clone());
                args.drain(..2);
            }
            _ => break,
        }
    }
    let Some(command) = args.first().cloned() else {
        return Err(USAGE.into());
    };
    let modules = &args[1..];
    let specs = load_specs(&specs_dir, modules)?;

    match command.as_str() {
        "gen" | "check" => {
            let mut clean = true;
            for spec in &specs {
                let text = match spec.module.as_str() {
                    "hex" => emit_hex_module(spec)?,
                    other => return Err(format!("no generator registered for module {other:?}")),
                };
                let path = target(&root, spec);
                let current = fs::read_to_string(&path).ok().map(|t| t.replace("\r\n", "\n"));
                let up_to_date = current.as_deref() == Some(text.as_str());
                let shown = path.strip_prefix(&root).unwrap_or(&path).display().to_string();
                if command == "gen" {
                    if !up_to_date {
                        if let Some(parent) = path.parent() {
                            fs::create_dir_all(parent).map_err(|e| format!("{shown}: {e}"))?;
                        }
                        fs::write(&path, &text).map_err(|e| format!("{shown}: {e}"))?;
                    }
                    println!("{} {shown}", if up_to_date { "unchanged" } else { "wrote    " });
                } else if up_to_date {
                    println!("ok    {shown}");
                } else {
                    clean = false;
                    println!("STALE {shown}");
                }
            }
            if !clean {
                eprintln!(
                    "golden files differ from the generator output; run:\n  cargo run \
                     --manifest-path tools/refgen/Cargo.toml -- gen"
                );
            }
            Ok(clean)
        }
        _ => Err(USAGE.into()),
    }
}

fn main() -> ExitCode {
    match run() {
        Ok(true) => ExitCode::SUCCESS,
        Ok(false) => ExitCode::FAILURE,
        Err(e) => {
            eprintln!("error: {e}");
            ExitCode::from(2)
        }
    }
}
